### ISSUE TITLE
Import error with latest requests (2.30) & urllib3 (2.0.2)

### ISSUE THREAD

**Issue by samionb** [allegroai/clearml#1010]
## Describe the bug
An ImportError is occurring during package import:

`Traceback (most recent call last):
  File "\myenv\lib\site-packages\clearml\utilities\requests_toolbelt\_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (\myenv\lib\site-packages\urllib3\contrib\__init__.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\env2\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\__init__.py", line 5, in <module>
    from .task import Task
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\task.py", line 44, in <module>
    from .backend_interface.metrics import Metrics
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\backend_interface\__init__.py", line 2, in <module>
    from .task import Task
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\backend_interface\task\__init__.py", line 1, in <module>
    from .task import Task
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\backend_interface\task\task.py", line 32, in <module>
    from ...binding.artifacts import Artifacts
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\binding\artifacts.py", line 23, in <module>
    from ..backend_interface.metrics.events import UploadEvent
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\backend_interface\metrics\__init__.py", line 2, in <module>
    from .interface import Metrics
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\backend_interface\metrics\interface.py", line 15, in <module>
    from ...storage.helper import StorageHelper
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\storage\__init__.py", line 2, in <module>
    from .manager import StorageManager
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\storage\manager.py", line 12, in <module>
    from .cache import CacheManager
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\storage\cache.py", line 12, in <module>
    from .helper import StorageHelper
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\storage\helper.py", line 35, in <module>
    from clearml.utilities.requests_toolbelt import MultipartEncoder
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\utilities\requests_toolbelt\__init__.py", line 12, in <module>
    from .multipart import (
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\utilities\requests_toolbelt\multipart\__init__.py", line 11, in <module>
    from .encoder import MultipartEncoder, MultipartEncoderMonitor
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\utilities\requests_toolbelt\multipart\encoder.py", line 17, in <module>
    from .._compat import fields
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "\myenv\lib\site-packages\clearml\utilities\requests_toolbelt\_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (\myenv\lib\site-packages\urllib3\contrib\__init__.py)
`

*Downgrading requests to 2.29 solves this issue.

## To reproduce
1. Create new venv.
2.  `pip install clearml`
3. Using Python, run: `from clearml import Task, Logger`

## Expected behaviour
Successfully completed error-free import.

## Environment
* ClearML SDK Version - `1.10.3`
* Python Version - `3.7`
* OS (**Windows**)
## Related Discussion
If this continues a slack thread, please provide a link to the original slack thread.

**Comment by jkhenning** [comment]
Hi @npit, ClearML SDK v1.10.4rc1 should fix this issue. An official version will be released next week.

**Comment by AlexandruBurlacu** [comment]
Hey @samionb, we released ClearML SDK 1.10.4 a couple of days ago, it fixes this issue
