### ISSUE TITLE
(Unauthorized (invalid credentials) (failed to locate provided credentials)) when running local docker server

### ISSUE THREAD

**Issue by Inquisitive-ME** [allegroai/clearml#1118]
## Describe the bug
I am unable to use ClearML with a local docker server.

I have setup a local server as described here:
https://clear.ml/docs/latest/docs/deploying_clearml/clearml_server_linux_mac/

I run
clearml-init and it seems successful:
```Detected credentials key="0XDP9VHCIAACX1U8LDTB" secret="hAGr***"
Port 8080 is the web port. Replacing 8080 with 8008 for API server

ClearML Hosts configuration:
Web App: http://localhost:8080
API: http://localhost:8008
File Store: http://localhost:8081

Verifying credentials ...
Credentials verified!

New configuration stored in /home/richard/clearml.conf
ClearML setup completed successfully.
```

But then when I try to track an experiment with:
```
from clearml import Task

task = Task.init(project_name='great project', task_name='best experiment')
```

 I get the following error:
```
2023-09-18 08:42:51,038 - clearml.Task - ERROR - Action failed <401/22: projects.get_all/v1.0 (Unauthorized (invalid credentials) (failed to locate provided credentials))> (name=^great\ project$, only_fields=['id'], shallow_search=False, search_hidden=True)
Traceback (most recent call last):
  File "/home/richard/.virtualenvs/deep_learning/lib/python3.10/site-packages/clearml/backend_interface/util.py", line 89, in get_or_create_project
    return _get_or_create_project(session, project_name, description=description, system_tags=system_tags, project_id=project_id)
  File "/home/richard/.virtualenvs/deep_learning/lib/python3.10/site-packages/clearml/backend_interface/util.py", line 103, in _get_or_create_project
    res = session.send(
  File "/home/richard/.virtualenvs/deep_learning/lib/python3.10/site-packages/clearml/backend_interface/base.py", line 109, in send
    return self._send(session=self.session, req=req, ignore_errors=ignore_errors, raise_on_errors=raise_on_errors,
  File "/home/richard/.virtualenvs/deep_learning/lib/python3.10/site-packages/clearml/backend_interface/base.py", line 103, in _send
    raise SendError(res, error_msg)
clearml.backend_interface.session.SendError: Action failed <401/22: projects.get_all/v1.0 (Unauthorized (invalid credentials) (failed to locate provided credentials))> (name=^great\ project$, only_fields=['id'], shallow_search=False, search_hidden=True)

```

## To reproduce
Follow Linux docker setup guide to create new clearML server

run `clearml-init `

run
```
from clearml import Task

task = Task.init(project_name='great project', task_name='best experiment')
```

## Expected behavior
I would expect that the project is created and tracking begins working

## Environment
* Server type self hosted 
* ClearML SDK Version: '1.12.2'
* ClearML Server Version  WebApp: 1.12.1-397 • Server: 1.12.1-397 • API: 2.26 
* OS Linux

**Comment by jkhenning** [comment]
Hi @Inquisitive-ME , can you share the `clearml.conf` file you have in your home folder?

**Comment by Inquisitive-ME** [comment]
from this issue I tried changing the default request method to POST but that didn't seem to solve the issue
https://github.com/allegroai/clearml/issues/517

**Comment by jkhenning** [comment]
This shouldn't matter unless you have some cloud ingress in the way (such as Google Cloud LBs).
Can you do `curl -u <key>:<secret> <api-server-address>` from the machine trying to connect to the server?

**Comment by jkhenning** [comment]
So what do you get if you do this?
`curl -u <key>:<secret> <api-server-address>/auth.login`

**Comment by Inquisitive-ME** [comment]
I get 
```
{"meta":{"id":"6ec98ec424e94b04958bf0171a57b913","trx":"6ec98ec424e94b04958bf0171a57b913","endpoint":{"name":"auth.login","requested_version":"2.26","actual_version":"1.0"},"result_code":200,"result_subcode":0,"result_msg":"OK","error_stack":"","error_data":{}},"data":{"token":"Long Token"
```

**Comment by jkhenning** [comment]
OK, this basically means the credentials are correct and you are communicating with the server successfully. The question is why will your SDK session start to use incorrect credentials in the middle of execution (or. alternatively, start using a different server)

**Comment by jkhenning** [comment]
Do you have any environment variables set when running the script? (those related to clearml)

**Comment by Inquisitive-ME** [comment]
I don't believe so.

From what I can tell by trying to debug in `backend_api/session/session.py` it appears that the username is the key from above and the password is the secret sometimes with `_send_request` is called but sometimes `_send_request` gets called with an auth object that does not have a username or password.

**Comment by jkhenning** [comment]
The first step is always using the key/secret to generate a token using the `auth.login` endpoint (which we've tried). After that, the token will be used to send requests. Also, the error you get can only be issued by the server if you're using key/secret and not when using a token, so the fact `projects.get_all` endpoint fails on this is very unusual since the SDK will never send it with explicit key/secret credentials

**Comment by jkhenning** [comment]
Can you try setting the `CLEARML_API_VERBOSE=1` env var and see if you get more in the task log?

**Comment by Inquisitive-ME** [comment]
Below is the additional logs I get
```
task = Task.init(project_name='great project 2', task_name='best experiment')
2023-09-19 12:06:25,073 - clearml.session - INFO - Refreshing token from http://192.168.99.24:8008 (access_key=87AQDMJ74FBK39Q5AIDY, exp=None)
2023-09-19 12:06:25,116 - clearml.session - INFO - Received new token
2023-09-19 12:06:25,200 - clearml.session - INFO - Refreshing token from http://192.168.99.24:8008 (access_key=87AQDMJ74FBK39Q5AIDY, exp=None)
2023-09-19 12:06:25,248 - clearml.session - INFO - Received new token
2023-09-19 12:06:25,270 - clearml.Task - ERROR - Action failed <401/22: projects.get_all/v1.0 (Unauthorized (invalid credentials) (failed to locate provided credentials))> (name=^great\ project\ 2$, only_fields=['id'], shallow_search=False, search_hidden=True)
2023-09-19 12:06:25,291 - clearml.session - INFO - Refreshing token from http://192.168.99.24:8008 (access_key=87AQDMJ74FBK39Q5AIDY, exp=None)
2023-09-19 12:06:25,322 - clearml.session - INFO - Received new token
2023-09-19 12:06:25,340 - clearml.Task - ERROR - Action failed <401/22: projects.get_all/v1.0 (Unauthorized (invalid credentials) (failed to locate provided credentials))> (name=^great\ project\ 2$, only_fields=['id'], shallow_search=False, search_hidden=True)
Traceback (most recent call last):
```

**Comment by jkhenning** [comment]
Perhaps attach the apiserver logs? Maybe there's a hint there?

**Comment by jenhaoyang** [comment]
I have similar issue, here is my apiserver logs
```bash
clearml-apiserver       | [2024-03-01 05:43:10,756] [8] [INFO] [clearml.service_repo] Returned 200 for auth.login in 5ms
clearml-apiserver       | [2024-03-01 05:43:10,778] [8] [WARNING] [clearml.service_repo] Returned 401 for projects.get_all in 1ms, msg=Unauthorized (invalid credentials) (failed to locate provided credentials)
clearml-apiserver       | [2024-03-01 05:43:10,788] [8] [INFO] [clearml.service_repo] Returned 200 for auth.login in 4ms
clearml-apiserver       | [2024-03-01 05:43:10,795] [8] [WARNING] [clearml.service_repo] Returned 401 for projects.get_all in 1ms, msg=Unauthorized (invalid credentials) (failed to locate provided credentials)
clearml-apiserver       | [2024-03-01 05:43:10,804] [8] [WARNING] [clearml.service_repo] Returned 401 for projects.get_all in 1ms, msg=Unauthorized (invalid credentials) (failed to locate provided credentials)
clearml-apiserver       | [2024-03-01 05:43:10,813] [8] [INFO] [clearml.service_repo] Returned 200 for auth.login in 4ms
clearml-apiserver       | [2024-03-01 05:43:10,820] [8] [WARNING] [clearml.service_repo] Returned 401 for projects.get_all in 1ms, msg=Unauthorized (invalid credentials) (failed to locate provided credentials)
```

**Comment by jkhenning** [comment]
@jenhaoyang how did you configure your SDK?

**Comment by jenhaoyang** [comment]
> @jenhaoyang how did you configure your SDK?  

Here is my [clearml.conf](https://github.com/allegroai/clearml/files/14475988/clearml.txt)

![image](https://github.com/allegroai/clearml/assets/7457532/a87dd7d5-7848-417b-987b-439264a1ed2b)

Here is SDK error log
```bash
Traceback (most recent call last):
  File "/home/ai_server/2005013/yolo_training/test_clearml.py", line 2, in <module>
    task = Task.init(project_name="my project", task_name="my task")
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/clearml/task.py", line 572, in init
    task = cls._create_dev_task(
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/clearml/task.py", line 3668, in _create_dev_task
    task = cls(
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/clearml/task.py", line 209, in __init__
    super(Task, self).__init__(**kwargs)
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/clearml/backend_interface/task/task.py", line 161, in __init__
    super(Task, self).__init__(id=task_id, session=session, log=log)
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/clearml/backend_interface/base.py", line 149, in __init__
    super(IdObjectBase, self).__init__(session, log, **kwargs)
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/clearml/backend_interface/base.py", line 41, in __init__
    self._session = session or self._get_default_session()
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/clearml/backend_interface/base.py", line 119, in _get_default_session
    InterfaceBase._default_session = Session(
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/clearml/backend_api/session/session.py", line 160, in __init__
    self._connect()
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/clearml/backend_api/session/session.py", line 227, in _connect
    self.refresh_token()
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/clearml/backend_api/session/token_manager.py", line 112, in refresh_token
    self._set_token(self._do_refresh_token(self.__token, exp=self.req_token_expiration_sec))
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/clearml/backend_api/session/session.py", line 863, in _do_refresh_token
    six.reraise(*sys.exc_info())
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/ai_server/2005013/yolo_training/venv/lib/python3.8/site-packages/clearml/backend_api/session/session.py", line 849, in _do_refresh_token
    raise LoginError(
clearml.backend_api.session.session.LoginError: Failed getting token (error 401 from http://192.168.8.149:8008): Unauthorized (invalid credentials) (failed to locate provided credentials)
```

**Comment by jingli-wtbox** [comment]
same issue for my server deployment. i found that i cannot add credentials using WebUI
![Screenshot 2024-04-11 at 4 23 50 PM](https://github.com/allegroai/clearml/assets/128546305/9512361f-22b8-435a-a1b7-9c6d5f6edd58)

**Comment by jingli-wtbox** [comment]
i do not know why the added credentials have disappeared.

**Comment by jingli-wtbox** [comment]
i found out how to fix it.

1. delete all files under /opt/clearml/data/
2. restart dockers
3. run your code again.

but you will lost all old data.

**Comment by ayooshk-phr** [comment]
@Inquisitive-ME Were you able to solve the bug?

**Comment by fedyhajali** [comment]
@Inquisitive-ME I have the same problem? Has anyone been able to solve it?

**Comment by jkhenning** [comment]
@fedyhajali "failed to locate provided credentials" indicates the server did get a key/secret pair, but could not locate the key in the database.
Can you try making this cURL call to see if it works?
```
curl -v -u "key:secret" <apiserver-address>/tasks.get_all
```

**Comment by Inquisitive-ME** [comment]
I was never able to solve this. For some reason this only happened to me on 1 computer and I could never figure it out what caused the issue or how to fix it.

**Comment by fedyhajali** [comment]
Ok, I tried calling `auth.login`, `tasks.get_all`, and `projects.get_all` from the command line, and everything works fine.

I also created a new, clean conda environment with only ClearML installed, but the issue persists—the same behavior occurs.

Debugging the code, I noticed that when the request for `projects.get_all` is created inside `session.py` file, the token is indeed included in the request headers. However, the response still returns a 401 Unauthorized error, which seems quite strange.

As a final test, I set up a new, clean virtual environment outside of conda (with venv module), and surprisingly, it works without issues. This suggests there might be a problem or conflict specific to my Anaconda environment.

For reference, I was using PyCharm with an environment created via conda.

**Comment by jkhenning** [comment]
I assume this is indeed something in your environment, since I'm using PyCharm for the last few years with ClearML and have not experienced any such issue...

**Comment by urbanclimatefr** [comment]
> [@fedyhajali](https://github.com/fedyhajali) "failed to locate provided credentials" indicates the server did get a key/secret pair, but could not locate the key in the database. Can you try making this cURL call to see if it works?
> 
> ```
> curl -v -u "key:secret" <apiserver-address>/tasks.get_all
> ```

Hi I am facing similiar [issue](https://github.com/clearml/clearml-server/issues/283), what do you mean by could not locate the key in the database? which database? thank you very much

**Comment by jkhenning** [comment]
@urbanclimatefr do you mean you've upgraded your server?
Also, where did you take the key/secret from?

**Comment by urbanclimatefr** [comment]
Yes, I copied old data from the clearml server 1.1, and upgraded the server to 1.17, I get the key, secrets by clearml-init, using the credentials created from (http://localhost:8080/settings/workspace-configuration)

**Comment by urbanclimatefr** [comment]
my clearml.conf looks like `# ClearML SDK configuration file
api {
    # Notice: 'host' is the api server (default port 8008), not the web server.
    api_server: http://localhost:8008/
    web_server: http://localhost:8080/
    files_server: http://localhost:8081/
    # Credentials are generated using the webapp, http://localhost:8080//settings
    # Override with os environment: CLEARML_API_ACCESS_KEY / CLEARML_API_SECRET_KEY
    credentials {"access_key": "key", "secret_key": "secret"}
}`
