### ISSUE TITLE
Open in Colab link in LangChain documentation leads to Not Found error

### ISSUE THREAD

**Issue by mdziezyc** [allegroai/clearml#1125]
## Describe the bug

No jupyter notebook under Open in Colab link

## To reproduce
1. Open https://python.langchain.com/docs/integrations/providers/clearml_tracking
2. Click "Open in Colab"

## Expected behaviour

```
Notebook not found
There was an error loading this notebook. Ensure that the file is accessible and try again.
Ensure that you have permission to view this notebook in GitHub and authorize Colaboratory to use the GitHub API.

https://github.com/hwchase17/langchain/blob/master/docs/ecosystem/clearml_tracking.html
Fetch for https://api.github.com/repos/hwchase17/langchain/contents/docs/ecosystem?per_page=100&ref=master failed: {
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/repos/contents#get-repository-content"
}

CustomError: Fetch for https://api.github.com/repos/hwchase17/langchain/contents/docs/ecosystem?per_page=100&ref=master failed: {
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/repos/contents#get-repository-content"
}

    at new cK (https://ssl.gstatic.com/colaboratory-static/common/a79e3d750d3220b6975940b845c5957c/external_polymer_binary.js:2288:68)
    at ra.program_ (https://ssl.gstatic.com/colaboratory-static/common/a79e3d750d3220b6975940b845c5957c/external_polymer_binary.js:2271:435)
    at ta (https://ssl.gstatic.com/colaboratory-static/common/a79e3d750d3220b6975940b845c5957c/external_polymer_binary.js:16:57)
    at ra.next_ (https://ssl.gstatic.com/colaboratory-static/common/a79e3d750d3220b6975940b845c5957c/external_polymer_binary.js:14:195)
    at laa.next (https://ssl.gstatic.com/colaboratory-static/common/a79e3d750d3220b6975940b845c5957c/external_polymer_binary.js:17:48)
    at b (https://ssl.gstatic.com/colaboratory-static/common/a79e3d750d3220b6975940b845c5957c/external_polymer_binary.js:17:309)
```

**Comment by ainoam** [comment]
Thanks for noting @mdziezyc - seems like the guys at [langchain](https://github.com/langchain-ai/langchain) have been  refactoring their docs repo over the past few months and broke some internal links - You can easily locate the notebook [here](https://github.com/langchain-ai/langchain/blob/master/docs/extras/integrations/providers/clearml_tracking.ipynb).

Would you care to PR the fix? (note at the end of the day this is an issue for the langchain repo)

**Comment by mdziezyc** [comment]
Fixed :)
