### ISSUE TITLE
LightGBM model loading fails when model is loaded from string

### ISSUE THREAD

**Issue by bedapisl** [allegroai/clearml#1135]
## Describe the bug
LightGBM model loading fails when model is loaded from string.

## To reproduce
Run the following script
``` 
import lightgbm as lgb
import clearml


task = clearml.Task.init(project_name="debug")

model_str = (
 'tree\n'
 'version=v3\n'
 'num_class=2\n'
 'num_tree_per_iteration=2\n'
 'label_index=0\n'
 'max_feature_idx=67\n'
 'objective=multiclass num_class:2\n'
 'feature_names=Column_0 Column_1 Column_2 Column_3 Column_4 Column_5 '
 'Column_6 Column_7 Column_8 Column_9 Column_10 Column_11 Column_12 Column_13 '
 'Column_14 Column_15 Column_16 Column_17 Column_18 Column_19 Column_20 '
 'Column_21 Column_22 Column_23 Column_24 Column_25 Column_26 Column_27 '
 'Column_28 Column_29 Column_30 Column_31 Column_32 Column_33 Column_34 '
 'Column_35 Column_36 Column_37 Column_38 Column_39 Column_40 Column_41 '
 'Column_42 Column_43 Column_44 Column_45 Column_46 Column_47 Column_48 '
 'Column_49 Column_50 Column_51 Column_52 Column_53 Column_54 Column_55 '
 'Column_56 Column_57 Column_58 Column_59 Column_60 Column_61 Column_62 '
 'Column_63 Column_64 Column_65 Column_66 Column_67\n'
 'feature_infos=[0:0.94567344221202154] [0:0.94567344221202154] [0:1] [0:1] '
 '[0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] '
 '[0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] '
 '[0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] '
 '[0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] '
 '[0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] [0:1] '
 '[0:1] [0:1] [0:1] [0:1]\n'
 'tree_sizes=1205 1227\n'
 '\n'
 'Tree=0\n'
 'num_leaves=10\n'
 'num_cat=0\n'
 'split_feature=2 0 0 1 2 0 1 0 1\n'
 'split_gain=150081 50105.1 41702.1 18884.2 5169.86 4417.24 5166.48 4398.13 '
 '4859.47\n'
 'threshold=0.026303009792495648 0.010459502024708998 1.0000000180025095e-35 '
 '0.0068344335345638446 0.019313976290741393 0.011935586586887889 '
 '0.01081722892715427 0.0040209572035367009 0.0050565925515789903\n'
 'decision_type=2 2 2 2 2 2 2 2 2\n'
 'left_child=1 2 -1 -3 5 -5 -7 -4 -9\n'
 'right_child=-2 3 7 4 -6 6 -8 8 -10\n'
 'leaf_value=-1.4086466613426223 -1.464078071702358 -1.4147130574932707 '
 '-1.4614413626878582 -1.4491134203599012 -1.4516240624567076 '
 '-1.4173027619213687 -1.4455730085091918 -1.4423554769823996 '
 '-1.4568072782148951\n'
 'leaf_weight=9457.6774541735649 164550.02481776476 41105.128059238195 '
 '20334.616381317377 4122.8900393545628 6941.3224308490753 9142.6845211088657 '
 '3605.55564057827 17877.815814673901 19412.95710003376\n'
 'leaf_count=26362 383033 100295 54884 7952 16868 20568 9002 45776 37731\n'
 'internal_value=-1.45133 -1.43545 -1.44757 -1.42292 -1.4371 -1.43112 -1.4253 '
 '-1.45396 -1.44988\n'
 'internal_weight=0 132001 67083.1 64917.6 23812.5 16871.1 12748.2 57625.4 '
 '37290.8\n'
 'internal_count=702471 319438 164753 154685 54390 37522 29570 138391 83507\n'
 'is_linear=0\n'
 'shrinkage=1\n'
 '\n'
 '\n'
 'Tree=1\n'
 'num_leaves=10\n'
 'num_cat=0\n'
 'split_feature=2 0 0 1 2 0 1 0 1\n'
 'split_gain=150081 50105.1 41702.1 18884.2 5169.86 4417.24 5166.48 4398.13 '
 '4859.47\n'
 'threshold=0.026303009792495648 0.010459502024708998 1.0000000180025095e-35 '
 '0.0068344335345638446 0.019313976290741393 0.011935586586887889 '
 '0.01081722892715427 0.0040209572035367009 0.0050565925515789903\n'
 'decision_type=2 2 2 2 2 2 2 2 2\n'
 'left_child=1 2 -1 -3 5 -5 -7 -4 -9\n'
 'right_child=-2 3 7 4 -6 6 -8 8 -10\n'
 'leaf_value=-0.30959728794279012 -0.25416587758305442 -0.30353089179214188 '
 '-0.25680258659755428 -0.26913052892551126 -0.26661988682870486 '
 '-0.30094118736404374 -0.27267094077622067 -0.27588847230301283 '
 '-0.26143667107051732\n'
 'leaf_weight=9457.6774541735649 164550.02481776476 41105.128059238195 '
 '20334.616381317377 4122.8900393545628 6941.3224308490753 9142.6845211088657 '
 '3605.55564057827 17877.815814673901 19412.95710003376\n'
 'leaf_count=26362 383033 100295 54884 7952 16868 20568 9002 45776 37731\n'
 'internal_value=-0.266909 -0.282795 -0.270673 -0.295321 -0.281148 -0.287126 '
 '-0.292946 -0.264285 -0.268365\n'
 'internal_weight=0 132001 67083.1 64917.6 23812.5 16871.1 12748.2 57625.4 '
 '37290.8\n'
 'internal_count=702471 319438 164753 154685 54390 37522 29570 138391 83507\n'
 'is_linear=0\n'
 'shrinkage=1\n'
 '\n'
 '\n'
 'end of trees\n'
 '\n'
 'feature_importances:\n'
 'Column_0=8\n'
 'Column_1=6\n'
 'Column_2=4\n'
 '\n'
 'parameters:\n'
 '[boosting: gbdt]\n'
 '[objective: multiclass]\n'
 '[metric: multi_error]\n'
 '[tree_learner: serial]\n'
 '[device_type: cpu]\n'
 '[data: ]\n'
 '[valid: ]\n'
 '[num_iterations: 1]\n'
 '[learning_rate: 0.02]\n'
 '[num_leaves: 10]\n'
 '[num_threads: 0]\n'
 '[deterministic: 0]\n'
 '[force_col_wise: 0]\n'
 '[force_row_wise: 0]\n'
 '[histogram_pool_size: -1]\n'
 '[max_depth: -1]\n'
 '[min_data_in_leaf: 20]\n'
 '[min_sum_hessian_in_leaf: 0.001]\n'
 '[bagging_fraction: 1]\n'
 '[pos_bagging_fraction: 1]\n'
 '[neg_bagging_fraction: 1]\n'
 '[bagging_freq: 0]\n'
 '[bagging_seed: 3]\n'
 '[feature_fraction: 1]\n'
 '[feature_fraction_bynode: 1]\n'
 '[feature_fraction_seed: 2]\n'
 '[extra_trees: 0]\n'
 '[extra_seed: 6]\n'
 '[early_stopping_round: 0]\n'
 '[first_metric_only: 0]\n'
 '[max_delta_step: 0]\n'
 '[lambda_l1: 0]\n'
 '[lambda_l2: 0]\n'
 '[linear_lambda: 0]\n'
 '[min_gain_to_split: 0]\n'
 '[drop_rate: 0.1]\n'
 '[max_drop: 50]\n'
 '[skip_drop: 0.5]\n'
 '[xgboost_dart_mode: 0]\n'
 '[uniform_drop: 0]\n'
 '[drop_seed: 4]\n'
 '[top_rate: 0.2]\n'
 '[other_rate: 0.1]\n'
 '[min_data_per_group: 100]\n'
 '[max_cat_threshold: 32]\n'
 '[cat_l2: 10]\n'
 '[cat_smooth: 10]\n'
 '[max_cat_to_onehot: 4]\n'
 '[top_k: 20]\n'
 '[monotone_constraints: ]\n'
 '[monotone_constraints_method: basic]\n'
 '[monotone_penalty: 0]\n'
 '[feature_contri: ]\n'
 '[forcedsplits_filename: ]\n'
 '[refit_decay_rate: 0.9]\n'
 '[cegb_tradeoff: 1]\n'
 '[cegb_penalty_split: 0]\n'
 '[cegb_penalty_feature_lazy: ]\n'
 '[cegb_penalty_feature_coupled: ]\n'
 '[path_smooth: 0]\n'
 '[interaction_constraints: ]\n'
 '[verbosity: 1]\n'
 '[saved_feature_importance_type: 0]\n'
 '[linear_tree: 0]\n'
 '[max_bin: 255]\n'
 '[max_bin_by_feature: ]\n'
 '[min_data_in_bin: 3]\n'
 '[bin_construct_sample_cnt: 200000]\n'
 '[data_random_seed: 1]\n'
 '[is_enable_sparse: 1]\n'
 '[enable_bundle: 1]\n'
 '[use_missing: 1]\n'
 '[zero_as_missing: 0]\n'
 '[feature_pre_filter: 1]\n'
 '[pre_partition: 0]\n'
 '[two_round: 0]\n'
 '[header: 0]\n'
 '[label_column: ]\n'
 '[weight_column: ]\n'
 '[group_column: ]\n'
 '[ignore_column: ]\n'
 '[categorical_feature: ]\n'
 '[forcedbins_filename: ]\n'
 '[precise_float_parser: 0]\n'
 '[objective_seed: 5]\n'
 '[num_class: 2]\n'
 '[is_unbalance: 0]\n'
 '[scale_pos_weight: 1]\n'
 '[sigmoid: 1]\n'
 '[boost_from_average: 1]\n'
 '[reg_sqrt: 0]\n'
 '[alpha: 0.9]\n'
 '[fair_c: 1]\n'
 '[poisson_max_delta_step: 0.7]\n'
 '[tweedie_variance_power: 1.5]\n'
 '[lambdarank_truncation_level: 30]\n'
 '[lambdarank_norm: 1]\n'
 '[label_gain: ]\n'
 '[eval_at: ]\n'
 '[multi_error_top_k: 1]\n'
 '[auc_mu_weights: ]\n'
 '[num_machines: 1]\n'
 '[local_listen_port: 12400]\n'
 '[time_out: 120]\n'
 '[machine_list_filename: ]\n'
 '[machines: ]\n'
 '[gpu_platform_id: -1]\n'
 '[gpu_device_id: -1]\n'
 '[gpu_use_dp: 0]\n'
 '[num_gpu: 1]\n'
 '\n'
 'end of parameters\n'
 '\n'
 'pandas_categorical:null\n'
)

model = lgb.Booster(model_str=model_str)
```
## Actual behaviour
Error:
``` 
ClearML Task: created new task id=42c1a1e58f0143a8be0900a33ffbfdc7
2023-10-12 14:04:15,435 - clearml.Task - INFO - No repository found, storing script code instead
ClearML results page: http://192.168.101.55:28080/projects/a6faf569467342289b574fb5f8b2b61a/experiments/42c1a1e58f0143a8be0900a33ffbfdc7/output/log
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    model = lgb.Booster(model_str=model_str)
  File "/home/pisl/.local/lib/python3.7/site-packages/clearml/binding/frameworks/__init__.py", line 36, in _inner_patch
    raise ex
  File "/home/pisl/.local/lib/python3.7/site-packages/clearml/binding/frameworks/__init__.py", line 34, in _inner_patch
    ret = patched_fn(original_fn, *args, **kwargs)
TypeError: _load() missing 1 required positional argument: 'model_file'
Failed auto-generating package requirements: exception SystemExit() not a BaseException subclass
```
## Expected behaviour
No error

## Note
If we add `model_file=None` to the constructor of lgb.Booster, like this:
```
model = lgb.Booster(model_file=None, model_str=model_str)
```
it works.

## Environment
* Server type: self hosted
* ClearML SDK Version: `1.12.2`
* Python Version: 3.7
* OS (Windows \ Linux \ Macos): Linux

## Comment
I think I can make a MR with fix for this if you want. It seems to be quite simple thing related to signature of `_load` function here: https://github.com/allegroai/clearml/blob/master/clearml/binding/frameworks/lightgbm_bind.py#L74.

**Comment by ainoam** [comment]
Thanks for reporting @bedapisl. We definitely welcome PRs if you're up for it.

**Comment by bedapisl** [comment]
Fix was merged: https://github.com/allegroai/clearml/pull/1136, closing.
