### ISSUE TITLE
OutputModel.config_dict causes "E   AttributeError: 'DummyModel' object has no attribute 'locked'"

### ISSUE THREAD

**Issue by dpinol** [allegroai/clearml#1243]
## Describe the bug
Exception when calling assigning config_dict to an offline Task.

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dani/.local/share/virtualenvs/sc-api-DipHMMiG/lib/python3.11/site-packages/clearml/model.py", line 2111, in config_dict
    self.update_design(config_dict=value)
  File "/home/dani/.local/share/virtualenvs/sc-api-DipHMMiG/lib/python3.11/site-packages/clearml/model.py", line 2697, in update_design
    if not self._validate_update():
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dani/.local/share/virtualenvs/sc-api-DipHMMiG/lib/python3.11/site-packages/clearml/model.py", line 2846, in _validate_update
    if self.id and self.published:
                   ^^^^^^^^^^^^^^
  File "/home/dani/.local/share/virtualenvs/sc-api-DipHMMiG/lib/python3.11/site-packages/clearml/model.py", line 2071, in published
    return self._get_base_model().locked
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DummyModel' object has no attribute 'locked'
```

## To reproduce

```
from clearml import OutputModel, Task
Task.set_offline(True)
_writer: Task = Task.init(project_name="test", task_name="task")
_curr_model = OutputModel(task=self._writer, name="curr")
_curr_model = OutputModel(task=_writer, name="curr")
_curr_model.config_dict = {"kk": 3}

## Expected behaviour
No error

## Environment
* Server type (app.clear.ml)
* ClearML SDK Version: 1.15.0
* Python Version: 3.11.5
* OS: Ubuntu 23.10

**Comment by ainoam** [comment]
Thanks for letting us know @dpinol - Hope to have a fix available soon.

**Comment by b5strbal** [comment]
I get the same error when trying to update model weights in offline mode:
```python
from clearml import Task, OutputModel

Task.set_offline(offline_mode=True)
task = Task.init(project_name="examples", task_name="my_task")

output_model = OutputModel(task=task, framework="PyTorch")

task.update_output_model(model_path='dummy.pth')
```
produces
```
Traceback (most recent call last):
  File "/p/project1/vsk49/balazs/clearml_debug.py", line 8, in <module>
    task.update_output_model(model_path='dummy.pth')
  File "/p/project1/vsk49/balazs/.venv/lib/python3.12/site-packages/clearml/backend_interface/task/task.py", line 1012, in update_output_model
    url = output_model.update_weights(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/vsk49/balazs/.venv/lib/python3.12/site-packages/clearml/model.py", line 2430, in update_weights
    if self.id and self.published:
                   ^^^^^^^^^^^^^^
  File "/p/project1/vsk49/balazs/.venv/lib/python3.12/site-packages/clearml/model.py", line 2071, in published
    return self._get_base_model().locked
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DummyModel' object has no attribute 'locked'
```
in clearml 1.15.0 all the way to the most recent 2.0.2 version.
