### ISSUE TITLE
Trains <=0.16.3 fresh install fails on PyJWT 2.0.0

### ISSUE THREAD

**Issue by jkhenning** [allegroai/clearml#268]
Due to a recent PyJWT major version (and a change in their interface) all Trains packages installed in a clean environment (i.e. one that does not have a previous PyJWT package installed) fail when executed with the following error:

```
Traceback (most recent call last):
  File "trains_task.py", line 3, in <module>
    task = Task.init()
  File "/home/foo/venv/lib/site-packages/trains/task.py", line 476, in init
    auto_connect_streams=auto_connect_streams,
  File "/home/foo/venv/lib/site-packages/trains/task.py", line 2264, in _create_dev_task
    log_to_backend=True,
  File "/home/foo/venv/lib/site-packages/trains/task.py", line 156, in __init__
    super(Task, self).__init__(**kwargs)
  File "/home/foo/venv/lib/site-packages/trains/trains/backend_interface/task/task.py", line 138, in __init__
    super(Task, self).__init__(id=task_id, session=session, log=log)
  File "/home/foo/venv/lib/site-packages/trains/backend_interface/base.py", line 131, in __init__
    super(IdObjectBase, self).__init__(session, log, **kwargs)
  File "/home/foo/venv/lib/site-packages/trains/backend_interface/base.py", line 34, in __init__
    self._session = session or self._get_default_session()
  File "/home/foo/venv/lib/site-packages/trains/backend_interface/base.py", line 105, in _get_default_session
    secret_key=ENV_SECRET_KEY.get(),
  File "/home/foo/venv/lib/site-packages/trains/backend_api/session/session.py", line 171, in __init__
    self.refresh_token()
  File "/home/foo/venv/lib/site-packages/trains/backend_api/session/token_manager.py", line 95, in refresh_token
    self._set_token(self._do_refresh_token(self.__token, exp=self.req_token_expiration_sec))
  File "/home/foo/venv/lib/site-packages/trains/backend_api/session/token_manager.py", line 77, in _set_token
    self.__token_expiration_sec = self._get_token_exp(token)
  File "/home/foo/venv/lib/site-packages/trains/backend_api/session/token_manager.py", line 72, in _get_token_exp
    return jwt.decode(token, verify=False).get('exp', sys.maxsize)
  File "/home/foo/venv/lib/site-packages/jwt/api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/home/foo/venv/lib/site-packages/jwt/api_jwt.py", line 80, in decode_complete
    'It is required that you pass in a value for the "algorithms" argument when calling decode().'
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
```

This does not occur in the latest ClearML SDK (which replaces Trains)

**Comment by jkhenning** [comment]
To solve, after installing Trains using `pip install trains`, downgrade PyJWT to version 1.7.1 using `pip install pyjwt==1.7.1`
