### ISSUE TITLE
Existence of sdk.google.storage.credentials_json (GOOGLE_APPLICATION_CREDENTIALS) without storage credentials inside throws an exception

### ISSUE THREAD

**Issue by johnml1135** [allegroai/clearml#331]
https://github.com/allegroai/clearml/blob/3e61e3b39bf6038435d24f8d62419d8d28f266d3/clearml/backend_config/bucket_config.py#L245

I have a google application credentials for a non-storage google service only.  While the agent correctly identified the json based google credentials (during configuration), it failed when running the task (see stacktrace below).  ClearML should gracefully keep going if the google credentials are present but missing storage credentials.

```
Environment setup completed successfully
Starting Task Execution:
Traceback (most recent call last):
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\code\pytorch_mnist.py", line 14, in <module>
from clearml import Task, Logger
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\__init__.py", line 4, in <module>
from .task import Task
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\task.py", line 30, in <module>
from .backend_interface.metrics import Metrics
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\backend_interface\__init__.py", line 2, in <module>
from .task import Task
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\backend_interface\task\__init__.py", line 1, in <module>
from .task import Task
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\backend_interface\task\task.py", line 31, in <module>
from ...binding.artifacts import Artifacts
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\binding\artifacts.py", line 23, in <module>
from ..backend_interface.metrics.events import UploadEvent
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\backend_interface\metrics\__init__.py", line 2, in <module>
from .interface import Metrics
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\backend_interface\metrics\interface.py", line 14, in <module>
from ...storage.helper import StorageHelper
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\storage\__init__.py", line 2, in <module>
from .manager import StorageManager
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\storage\manager.py", line 13, in <module>
from .cache import CacheManager
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\storage\cache.py", line 7, in <module>
from .helper import StorageHelper
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\storage\helper.py", line 103, in <module>
class StorageHelper(object):
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\storage\helper.py", line 194, in StorageHelper
_gs_configurations = GSBucketConfigurations.from_config(config.get('google.storage', {}))
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\backend_config\bucket_config.py", line 245, in from_config
default_project = gs_configuration.get("project") or {}
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\utilities\pyhocon\config_tree.py", line 215, in get
return self._get(ConfigTree.parse_key(key), 0, default)
File "C:\Users\JohnLambert\.clearml\venvs-builds\3.8\lib\site-packages\clearml\utilities\pyhocon\config_tree.py", line 151, in _get
raise ConfigMissingException(u"No configuration setting found for key {key}".format(
clearml.utilities.pyhocon.exceptions.ConfigMissingException: 'No configuration setting found for key project'
```

**Comment by johnml1135** [comment]
I think I resolved it.  i had sdk.google.storage.credentials_json set in my agent, even though the file was bad.  I went into the agent's environment variables and deleted GOOGLE_APPLICATION_CREDENTIALS and restarted the clearml-agent.  This resolved the issue for me.

Still, the code should gracefully fail, not like what it does right now.  A little try...except never hurt anybody.

**Comment by bmartinn** [comment]
Hi @johnml1135 
Kudos on the quick solution!

Regrading the issue, I want to make sure I understand the setup.
Basically (if I got it right from the stack trace), the `import clearml` fails on parsing the config file `~/clearml.conf` , is that right ?

Regrading the graceful error recovery, although I generally agree with you (i.e. print a warning to console and continue running), I think there is a good point in saying the opposite. Meaning if your configuration file is incorrect, I want to crash (obviously with meaningful log/error), because I need to fix my config file  as soon as possible. 

I think the strongest point in the argument that we should crash on such errors, is that "silent" recovery could very easily be missed. As a followup, the question should be, let's assume we pass that stage, what shall we do when we actually need to use the credentials, imagine uploading/downloading from `gs://bucket`, should we silently return None / should we raise an exception, 
wdyt ?

**Comment by johnml1135** [comment]
I have credentials for using the google translate api, which are correct credentials.  For some reason though, it was failing on them.  Here is my credential file (with the keys removed, obviously):

```
{
  "type": "service_account",
  "project_id": "xxxxxxxxxxxxxxx",
  "private_key_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n-----END PRIVATE KEY-----\n",
  "client_email": "xxxxxxxxxxxxxxxxxxxxxxx",
  "client_id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}

```

**Comment by bmartinn** [comment]
> I have credentials for using the google translate api,

So in theory, `clearml` should not be aware of those credentials (since these are not storage credentials), but are you saying that the same file is used for both storage credentials and google service API credentials ? (obviously if this is the case it should not crash)

**Comment by johnml1135** [comment]
Yes, at least as far as google uses the environment variable "GOOGLE_APPLICATION_CREDENTIALS" for both the google service API and the storage credentials.  The clearml-agent finds the environment variable and then registers the "sdk.google.storage.credentials_json" parameter.

**Comment by bmartinn** [comment]
Hmm that is a good point. Okay I'm definitely with you, if there is no section for storage at all, it should only output a warning, so at least you have visibility. sounds good ?

**Comment by johnml1135** [comment]
That sounds fine to me.  Warning (or info?) is better than exceptions. If there is a google credential in the system and there is no storage there, it would be odd and worth noting in the log.

**Comment by bmartinn** [comment]
> Warning (or info?)

Yes, I'm not sure either... anyhow they look pretty much the same on the console output :)
Fix will be committed soon, I'll update here once we have an RC with the fix

**Comment by bmartinn** [comment]
Hi @johnml1135 
A fix was pushed, you can test with the latest from the main branch (RC coming soon)
```
pip install git+https://github.com/allegroai/clearml.git
```
