### ISSUE TITLE
Over corporate proxy

### ISSUE THREAD

**Issue by ngockhanh5110** [allegroai/clearml#341]
I am having corporate server as an agent. All internet accesses have to go through a proxy. I was struggling deploy ClearML server on premise but managed to connect the agent to another online host ClearML server. 

But when queuing tasks and running task online, I got this issue. I ran `clearml-agent daemon`, one within docker (passed env vars) and the other without docker, but both of them had this problem.

Can you help me please?

`Traceback (most recent call last):
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_api/session/session.py", line 605, in _do_refresh_token
res = self._send_request(
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_api/session/session.py", line 245, in _send_request
res = self.__http_session.request(
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_api/utils.py", line 85, in send
return super(SessionWithTimeout, self).send(request, **kwargs)
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 696, in urlopen
self._prepare_proxy(conn)
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
conn.connect()
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/urllib3/connection.py", line 359, in connect
conn = self._connect_tls_proxy(hostname, conn)
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/urllib3/connection.py", line 500, in _connect_tls_proxy
return ssl_wrap_socket(
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 432, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 474, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock)
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/ssl.py", line 997, in _create
raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/u01/vt_media/.clearml/venvs-builds/3.8/code/stage_one.py", line 2, in <module>
task = Task.init(project_name="pipeline", task_name="pipeline step 1 dataset artifact")
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/task.py", line 508, in init
task = cls(
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/task.py", line 159, in __init__
super(Task, self).__init__(**kwargs)
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_interface/task/task.py", line 146, in __init__
super(Task, self).__init__(id=task_id, session=session, log=log)
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_interface/base.py", line 131, in __init__
super(IdObjectBase, self).__init__(session, log, **kwargs)
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_interface/base.py", line 34, in __init__
self._session = session or self._get_default_session()
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_interface/base.py", line 101, in _get_default_session
InterfaceBase._default_session = Session(
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_api/session/session.py", line 171, in __init__
self.refresh_token()
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_api/session/token_manager.py", line 104, in refresh_token
self._set_token(self._do_refresh_token(self.__token, exp=self.req_token_expiration_sec))
File "/u01/vt_media/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_api/session/session.py", line 637, in _do_refresh_token
raise LoginError('Unrecognized Authentication Error: {} {}'.format(type(ex), ex))
clearml.backend_api.session.session.LoginError: Unrecognized Authentication Error: <class 'ValueError'> check_hostname requires server_hostname`

**Comment by jkhenning** [comment]
Hi @ngockhanh5110,

How did you configure the proxy?

**Comment by ngockhanh5110** [comment]
> Hi @ngockhanh5110,
> 
> How did you configure the proxy?

I do `export https_proxy=<corporate proxy>`

**Comment by jkhenning** [comment]
I assume `<corporate proxy>` it's in the form of `https://...`?

**Comment by jkhenning** [comment]
Also, can you see the `urllib3` version?

**Comment by ngockhanh5110** [comment]
> I assume `<corporate proxy>` it's in the form of `https://...`?

yes that's right.



> Also, can you see the `urllib3` version?

I will check it later, but how does it affect on the running? I assume it was the most updated.

**Comment by ngockhanh5110** [comment]
I think it probably is an issue from `urllib3`. I wonder whether or not should I state `https_proxy` some where in the conf file.

**Comment by jkhenning** [comment]
I think it's because the latest versions of `urllib3` do not allow schema in this value... see https://stackoverflow.com/a/67000726

**Comment by bmartinn** [comment]
@ngockhanh5110 seems like this one #293 , no?

**Comment by ngockhanh5110** [comment]
> @ngockhanh5110 seems like this one #293 , no?

That issue solve docker connection, not container connection, I passed it.


> I think it's because the latest versions of `urllib3` do not allow schema in this value... see https://stackoverflow.com/a/67000726

Thank mate, it solved my problem.
