### ISSUE TITLE
Bug in hydra_bind.py

### ISSUE THREAD

**Issue by mhnatiuk** [allegroai/clearml#362]
```
In [10]: clearml.__version__
Out[10]: '1.0.2'
```

When patching Hydra, somebody used positional arguments in wrong order:

hydra_bind.py:
```
   @staticmethod
    def _patched_run_job(config, task_function, *args, **kwargs):
        # store the config
        # noinspection PyBroadException
        try:
            if running_remotely():
                # we take care of it in the hydra run (where we have access to the overrides)
                pass
            else:
                overrides = config.hydra.overrides.task
                stored_config = dict(arg.split('=', 1) for arg in overrides)
                stored_config[PatchHydra._parameter_allow_full_edit] = False
                if PatchHydra._current_task:
                    PatchHydra._current_task.connect(stored_config, name=PatchHydra._parameter_section)
                    PatchHydra._last_untracked_state.pop('connect', None)
                else:
                    PatchHydra._last_untracked_state['connect'] = dict(
                        mutable=stored_config, name=PatchHydra._parameter_section)
                # todo: remove the overrides section from the Args (we have it here)
                # PatchHydra._current_task.delete_parameter('Args/overrides')
        except Exception:
            pass

        pre_app_task_init_call = bool(PatchHydra._current_task)

        if pre_app_task_init_call:
            LoggerRoot.get_base_logger(PatchHydra).info(
                'Task.init called outside of Hydra-App. For full Hydra multi-run support, '
                'move the Task.init call into the Hydra-App main function')
        

        ########## HERE ############
        result = PatchHydra._original_run_job(
            config, partial(PatchHydra._patched_task_function, task_function,),
            *args, **kwargs)

 ```

should be:

```
        result = PatchHydra._original_run_job(
            config=config,
            task_function=partial(
                PatchHydra._patched_task_function,
                task_function,
            ),
            *args,
            **kwargs
        )
```      

That causes inability to run hydra job when even having clearml code in it. I believe that patching hydra is somehow a poor design choice, but you must have your reasons :)

```
Traceback (most recent call last):
  File "mlops/main.py", line 118, in <module>
    run()  # pylint: disable=no-value-for-parameter
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/mlops-hoCmpqgV-py3.8/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/mlops-hoCmpqgV-py3.8/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/mlops-hoCmpqgV-py3.8/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/mlops-hoCmpqgV-py3.8/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/mlops-hoCmpqgV-py3.8/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/mlops-hoCmpqgV-py3.8/lib/python3.8/site-packages/clearml/binding/hydra_bind.py", line 89, in _patched_hydra_run
    return PatchHydra._original_hydra_run(self, config_name, task_function, overrides, *args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/mlops-hoCmpqgV-py3.8/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 97, in run
    ret = run_job(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/mlops-hoCmpqgV-py3.8/lib/python3.8/site-packages/clearml/binding/hydra_bind.py", line 121, in _patched_run_job
    result = PatchHydra._original_run_job(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/mlops-hoCmpqgV-py3.8/lib/python3.8/site-packages/hydra/core/utils.py", line 123, in run_job
    HydraConfig.instance().set_config(config)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/mlops-hoCmpqgV-py3.8/lib/python3.8/site-packages/hydra/core/hydra_config.py", line 15, in set_config
    OmegaConf.set_readonly(cfg.hydra, True)
AttributeError: 'functools.partial' object has no attribute 'hydra'
```

**Comment by mhnatiuk** [comment]
I hope i saved you guys some debugging time, I'm actually in process of going with clearml into serious ML pipelines, so I won't conceal that I'm eager to submit MR

**Comment by mhnatiuk** [comment]
Apparently fixed on master. Excuse me guys

**Comment by bmartinn** [comment]
@mhnatiuk no worries, and thank you for the suggesting PR-ing a fix!
Please feel free to PR anything you think will be of value to you or other users, it is always welcomed :)
