### ISSUE TITLE
helper.check_write_permissions is not threadsafe

### ISSUE THREAD

**Issue by aljeshishe** [allegroai/clearml#394]
helper.check_write_permissions creates file .clearml.test on dest_path and then removes it.
This is not thread-safe and could lead to exception in following scenario:
1. Task 1 and 2 start helper.check_write_permissions with same dest_path
2. Task 1 and 2 create .clearml.test 
3. Task 1 removes .clearml.test
4. Task 2 tries to remove .clearml.test but fails with exception:
```
Traceback (most recent call last):
  File "/root/.clearml/venvs-builds/3.6/lib/python3.6/site-packages/clearml/storage/helper.py", line 770, in check_write_permissions
    self.delete(path=dest_path)
  File "/root/.clearml/venvs-builds/3.6/lib/python3.6/site-packages/clearml/storage/helper.py", line 759, in delete
    return self._driver.delete_object(self._get_object(path))
  File "/root/.clearml/venvs-builds/3.6/lib/python3.6/site-packages/clearml/storage/helper.py", line 1545, in delete_object
    object.delete()
  File "/root/.clearml/venvs-builds/3.6/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 770, in delete
    retry=retry,
  File "/root/.clearml/venvs-builds/3.6/lib/python3.6/site-packages/google/cloud/storage/bucket.py", line 1568, in delete_blob
    _target_object=None,
  File "/root/.clearml/venvs-builds/3.6/lib/python3.6/site-packages/google/cloud/storage/client.py", line 679, in _delete_resource
    _target_object=_target_object,
  File "/root/.clearml/venvs-builds/3.6/lib/python3.6/site-packages/google/cloud/storage/_http.py", line 78, in api_request
    return call()
  File "/root/.clearml/venvs-builds/3.6/lib/python3.6/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/rc-sandbox/o/samples%2Foutputs%2F.clearml.test?prettyPrint=false: No such object: rc-sandbox/samples/outputs/.clearml.test
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "../mnist_torch/mnist_torch.py", line 90, in <module>
    main()
  File "../mnist_torch/mnist_torch.py", line 50, in main
    task = clearml.Task.init(project_name='grachev', task_name='Mnist on pytorch')
  File "/root/.clearml/venvs-builds/3.6/lib/python3.6/site-packages/clearml/task.py", line 519, in init
    task.output_uri = cls.__default_output_uri
  File "/root/.clearml/venvs-builds/3.6/lib/python3.6/site-packages/clearml/task.py", line 812, in output_uri
    helper.check_write_permissions(value)
  File "/root/.clearml/venvs-builds/3.6/lib/python3.6/site-packages/clearml/storage/helper.py", line 772, in check_write_permissions
    raise ValueError('Insufficient permissions for {}'.format(base_url))
ValueError: Insufficient permissions for gs://rc-sandbox/samples/outputs
```

**Comment by jkhenning** [comment]
Hi @aljeshishe,

Thanks for reporting this, we'll add some protection against this scenario 🙂
