### ISSUE TITLE
invalid `task_name`

### ISSUE THREAD

**Issue by patzm** [allegroai/clearml#417]
A `task_name=0` for instance seems to be invalid. Also `ab` or `01`. I looked a bit into the code and couldn't find where this condition is defined. Can you document which `task_name`s are valid?

```python-traceback
Traceback (most recent call last):
...
   self._clear_ml_task = Task.init(project_name=project_name, task_name=task_name, tags=tags)
  File "/usr/local/lib/python3.6/dist-packages/clearml/task.py", line 496, in init
    auto_connect_streams=auto_connect_streams,
  File "/usr/local/lib/python3.6/dist-packages/clearml/task.py", line 2530, in _create_dev_task
    log_to_backend=True,
  File "/usr/local/lib/python3.6/dist-packages/clearml/task.py", line 163, in __init__
    super(Task, self).__init__(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clearml/backend_interface/task/task.py", line 167, in __init__
    self.id = self._auto_generate(project_name=project_name, task_name=task_name, task_type=task_type)
  File "/usr/local/lib/python3.6/dist-packages/clearml/backend_interface/task/task.py", line 326, in _auto_generate
    res = self.send(req)
  File "/usr/local/lib/python3.6/dist-packages/clearml/backend_interface/base.py", line 96, in send
    log=self.log, async_enable=async_enable)
  File "/usr/local/lib/python3.6/dist-packages/clearml/backend_interface/base.py", line 89, in _send
    raise SendError(res, error_msg)
clearml.backend_interface.session.SendError: Action failed <400/800: tasks.create/v1.0 (Data validation error: name=String value is too short)> (name=0, system_tags=['development'], type=training, comment=Auto-generated at 2021-08-02 15:31:05 UTC by root@XXX, project=XXXX, input={'view': {}})
```

I am using ClearML `v1.0.4`. The server is now running `v1.1`.

**Comment by jkhenning** [comment]
Hi @patzm ,

The minimum length for a task name is 3 characters - I'll make sure we update it somewhere 🙂

**Comment by patzm** [comment]
nice thanks :+1:
