### ISSUE TITLE
clearml is not compatible with click.argument

### ISSUE THREAD

**Issue by exzhawk** [allegroai/clearml#437]
### Steps to reproduce:
1. install latest click `pip install click==8.0.1`
1. install latest clearml `pip install git+https://github.com/allegroai/clearml.git@569ab6610d32b2e00a8c56561357862fa357a460`
1. run code below with command `python3 main.py test_dataset`
```python
#!/usr/bin/env python3
import clearml
import click

@click.command()
@click.argument('--dataset', type=str)
def main(dataset):
    print(dataset)


if __name__ == '__main__':
    main()
```
result
```bash
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    @click.argument('--dataset', type=str)
  File "/home/username/.local/lib/python3.6/site-packages/click/decorators.py", line 184, in decorator
    cmd = _make_command(f, name, attrs, cls)  # type: ignore
  File "/home/username/.local/lib/python3.6/site-packages/click/decorators.py", line 152, in _make_command
    **attrs,
  File "/home/username/.local/lib/python3.6/site-packages/clearml/binding/frameworks/__init__.py", line 36, in _inner_patch
    raise ex
  File "/home/username/.local/lib/python3.6/site-packages/clearml/binding/frameworks/__init__.py", line 34, in _inner_patch
    ret = patched_fn(original_fn, *args, **kwargs)
  File "/home/username/.local/lib/python3.6/site-packages/clearml/binding/click.py", line 92, in _command_init
    if option.help:
AttributeError: 'Argument' object has no attribute 'help'
```

looks like `click.option` is supported but not `click.argument`

**Comment by exzhawk** [comment]
Works well! Hoping there will be a new release soon.
