### ISSUE TITLE
Offline mode checks server configuration

### ISSUE THREAD

**Issue by dmus** [allegroai/clearml#489]
To reproduce:

```
import os
from clearml import Task

parameters = {
    'experiment': {
        'project_name': 'test',
        'experiment_name': 'test_exp',
        'tags': []
    }
}

Task.set_offline(True)
if not Task.is_offline():
    os.environ['CLEARML_NO_DEFAULT_SERVER'] = '1'
task = Task.init(
    project_name=parameters['experiment']['project_name'],
    task_name=parameters['experiment']['experiment_name'],
    task_type='testing',
    tags=parameters['experiment']['tags'],
    auto_connect_arg_parser=True,
    auto_connect_streams=True,
    auto_connect_frameworks=True,
    auto_resource_monitoring=True,
)
task.connect_configuration(parameters)
```

This gives:

> ValueError: ClearML configuration could not be found (missing `~/clearml.conf` or Environment CLEARML_API_HOST)
> To get started with ClearML: setup your own `clearml-server`, or create a free account at https://app.community.clear.ml

I would expect that offline mode is not checking for a server

**Comment by jkhenning** [comment]
@dmus a fix was pushed to the main branch, we'll update when a version that includes it is released 🙂

**Comment by aravinthk00** [comment]
Hi , I also encountered same issue and used update version of ClearML .

My Error Log : 

Traceback (most recent call last):
  File "C:\Users\30863\Project\dataset\yolov5\train.py", line 630, in <module>
    main(opt)
  File "C:\Users\30863\Project\dataset\yolov5\train.py", line 526, in main
    train(opt.hyp, opt, device, callbacks)
  File "C:\Users\30863\Project\dataset\yolov5\train.py", line 93, in train
    loggers = Loggers(save_dir, weights, opt, hyp, LOGGER)  # loggers instance
  File "C:\Users\30863\Project\dataset\yolov5\utils\loggers\__init__.py", line 106, in __init__
    self.clearml = ClearmlLogger(self.opt, self.hyp)
  File "C:\Users\30863\Project\dataset\yolov5\utils\loggers\clearml\clearml_utils.py", line 86, in __init__
    self.task = Task.init(
  File "C:\Users\30863\Anaconda3\lib\site-packages\clearml\task.py", line 583, in init
    task = cls._create_dev_task(
  File "C:\Users\30863\Anaconda3\lib\site-packages\clearml\task.py", line 3035, in _create_dev_task
    task = cls(
  File "C:\Users\30863\Anaconda3\lib\site-packages\clearml\task.py", line 183, in __init__
    super(Task, self).__init__(**kwargs)
  File "C:\Users\30863\Anaconda3\lib\site-packages\clearml\backend_interface\task\task.py", line 155, in __init__
    super(Task, self).__init__(id=task_id, session=session, log=log)
  File "C:\Users\30863\Anaconda3\lib\site-packages\clearml\backend_interface\base.py", line 145, in __init__
    super(IdObjectBase, self).__init__(session, log, **kwargs)
  File "C:\Users\30863\Anaconda3\lib\site-packages\clearml\backend_interface\base.py", line 39, in __init__
    self._session = session or self._get_default_session()
  File "C:\Users\30863\Anaconda3\lib\site-packages\clearml\backend_interface\base.py", line 115, in _get_default_session
    InterfaceBase._default_session = Session(
  File "C:\Users\30863\Anaconda3\lib\site-packages\clearml\backend_api\session\session.py", line 178, in __init__
    raise ValueError(
ValueError: ClearML configuration could not be found (missing `~/clearml.conf` or Environment CLEARML_API_HOST)
To get started with ClearML: setup your own `clearml-server`, or create a free account at https://app.clear.ml/


My Snippet Code : 

 if not self._offline_mode and ENV_CLEARML_NO_DEFAULT_SERVER.get() and host == self.default_demo_host:
            raise ValueError(
                "ClearML configuration could not be found (missing `~/clearml.conf` or Environment CLEARML_API_HOST)\n"
                "To get started with ClearML: setup your own `clearml-server`, "
                "or create a free account at https://app.clear.ml"
            )

**Comment by jkhenning** [comment]
Hi @aravinthk00, did you set the offline mode? You can do that by setting `CLEARML_OFFLINE_MODE=1`

**Comment by kumartankhush786** [comment]
After do offline i got upload zip file. I don't understand where to upload can you please explain? Thanks!

**Comment by erezalg** [comment]
Hi @kumartankhush786,

Sorry for the slow answer, were you able to get what you wanted to work?
If not, please elaborate on what the need is and I'll try to help!

**Comment by jkhenning** [comment]
Closing this issue due to inactivity. Please reopen if required.
