### ISSUE TITLE
log multiple models in the same process

### ISSUE THREAD

**Issue by davidenitti** [allegroai/clearml#564]
I have a training script where multiple models are training at the same time, is it possible to log every model independently as I was training N different training scripts? how should I modify Task.init for this?
thanks!

**Comment by davidenitti** [comment]
thanks, but I need to have a separate task so I have kpi results for each model I train. I found a solution using task.init to create a main task and task.create with base_task_id=main_task.task_id and changing the name of the child tasks with set_name.

**Comment by davidenitti** [comment]
@jkhenning as I said I found a solution using Task.init to create the main experiment and 
```
task_dict[name_net] = Task.create(project_name=project_name,task_name=args_main['name'] + " " + name_net, ase_task_id=main_task.task_id)
```
 to create the children tasks, one for each model. but now I have another issue, it does not work in offline mode:
```
    task_dict[name_net] = Task.create(project_name=project_name,task_name=args_main['name'] + " " + name_net, base_task_id=main_task.task_id)
  File "/home/davide/.local/lib/python3.8/site-packages/clearml/task.py", line 727, in create
    task = manual_populate.create_task()
  File "/home/davide/.local/lib/python3.8/site-packages/clearml/backend_interface/task/populate.py", line 185, in create_task
    task = Task.clone(source_task=self.base_task_id, project=Task.get_project_id(self.project_name))
  File "/home/davide/.local/lib/python3.8/site-packages/clearml/task.py", line 1057, in clone
    cloned_task_id = cls._clone_task(cloned_task_id=task_id, name=name, comment=comment,
  File "/home/davide/.local/lib/python3.8/site-packages/clearml/backend_interface/task/task.py", line 2184, in _clone_task
    cloned_task_id = res.response.id
AttributeError: 'NoneType' object has no attribute 'response'

```

**Comment by jkhenning** [comment]
Hi @davidenitti ,

Nice solution 🙂 

I'll take a look at the offline issue and get back to you

**Comment by davidenitti** [comment]
any update on this? thanks!

**Comment by jkhenning** [comment]
I think cloning a task with a `base_task_id` (which is what you call to Task.create is calling) is not supported in offline mode - can you try without the `base_task_id`?

**Comment by davidenitti** [comment]
@jkhenning I get the same error but on Task.get_task I call before Task.create
```
Traceback (most recent call last):
  File "train.py", line 955, in <module>
    main(args)
  File "train.py", line 749, in main
    main_task, task_dict = init_clearml(copy.deepcopy(vars(args)))
  File "train.py", line 620, in init_clearml
    task_dict[name_net] = Task.get_task(project_name=project_name, task_name=args_main['name'] + " " + name_net)
  File "/usr/local/lib/python3.6/dist-packages/clearml/task.py", line 793, in get_task
    include_archived=allow_archived, task_filter=task_filter,
  File "/usr/local/lib/python3.6/dist-packages/clearml/task.py", line 3508, in __get_task
    project = get_single_result(entity='project', query=project_name, results=res.response.projects)
AttributeError: 'NoneType' object has no attribute 'response'
```
maybe get_task does not work offline?

**Comment by jkhenning** [comment]
Yeah, offline mode was designed to send all communication to some buffer that can be later uploaded to the server. This is possible when you have outgoing calls (and you assume they were successful), but can pose a problem when you have calls that try to retrieve data from the server - there's no way for offline mode to return something you can actually use in the get_task response...
