### ISSUE TITLE
Environment on remote machine does not detect a GPU

### ISSUE THREAD

**Issue by Xallt** [allegroai/clearml#600]
Hello,
My issue is with the remote task execution.
I have an experiment powered by `pytorch_lightning`.
I have a task that works fine if I don't run `task.execute_remotely`

However, when running the command from above on a machine that has a GPU:
```
$ nvidia-smi
Wed Mar  9 11:01:18 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:8B:00.0 Off |                    0 |
| N/A   41C    P0    22W / 300W |      4MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I get this error on the command `pl.Trainer(gpus=1, max_epochs=args.max_epochs, logger=logger, callbacks=[clearml_model_checkpoint])`:

```
Traceback (most recent call last):
  File "train-clearml.py", line 129, in <module>
    trainer = pl.Trainer(gpus=1, max_epochs=args.max_epochs, logger=logger, callbacks=[clearml_model_checkpoint])
  File "/home/ml-backend/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 38, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/ml-backend/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 426, in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
  File "/home/ml-backend/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1539, in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
  File "/home/ml-backend/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 89, in parse_gpu_ids
    return _sanitize_gpu_ids(gpus)
  File "/home/ml-backend/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 151, in _sanitize_gpu_ids
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0]
 But your machine only has: []
```

BUT if I log into the machine, create an environment with `python3.8 -m venv` and install pytorch there, `torch.cuda.is_available()` returns `True`

CUDA version 11
torch==1.9.1
Nvidia Driver Version: 455.23.05

**Comment by jkhenning** [comment]
Hi @Xallt ,

How exactly are you running the task on that machine? Is it using a ClearML Agent?

**Comment by Xallt** [comment]
@jkhenning 
I have an agent on a separate machine that is run with
```
clearml-agent daemon --gpus 1 --queue gpu
```

I then execute the task remotely by running a script from my machine that has a line `task.execute_remotely(queue='gpu')`

I don't know if this is relevant, but looking at the 'Workers' page this is what I see:
![image](https://user-images.githubusercontent.com/24624181/157440492-51e47090-27bb-44dc-80a6-406bd717d979.png)
There's no plot for GPU usage at any point in time.

Does it mean that the problem lies in how `clearml-agent` environment sees GPUs and not in the torch, CUDA versions?

**Comment by jkhenning** [comment]
@Xallt when using the command:
```bash
clearml-agent daemon --gpus 1 --queue gpu
```

You're basically asking the agent to use GPU number 1 - the `--gpus` switch is used to specify active GPUs for the daemon to use, and is equivalent to setting NVIDIA_VISIBLE_DEVICES (for example `--gpus 0` or `--gpu 0,1,2` or `--gpus all`), so in your case I assume you actually want to specify `--gpus 0`?

**Comment by Xallt** [comment]
@jkhenning 
Wow, I think that fixed it. That was easy)
Yeah, made the mistake of copying the command from somewhere without fully understanding it.

Thanks a lot!
