### ISSUE TITLE
Error after 2-line Code Integration

### ISSUE THREAD

**Issue by demcbs** [allegroai/clearml#607]
Hi,

I used the following two (recommended) lines in my otherwise (when not integrating ClearML) functioning image segmentation training script (which besides ClearML uses Pytorch Lightning, MONAI and Tensorboard.)
```
from clearml import Task
task = Task.init(project_name="testproject", task_name="testtask")
```
ClearML succesfully displays my Tensorboard logs and machine monitoring which is great. However, it throws the below errors constantly in the training process and I do not know what it means/why it occurs.

Any help is greatly appreciated.

Thanks!

```
Exception ignored in: <function _after_at_fork_child_reinit_locks at 0x7fdace5bcaf0>
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 255, in _after_at_fork_child_reinit_locks


Traceback (most recent call last):
Exception ignored in: <function _after_at_fork_child_reinit_locks at 0x7fdace5bcaf0>    Exception ignored in: handler._at_fork_reinit()Traceback (most recent call last):

<function _after_at_fork_child_reinit_locks at 0x7fdace5bcaf0>  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 255, in _after_at_fork_child_reinit_locks
    handler._at_fork_reinit()Exception ignored in: Traceback (most recent call last):
<function _after_at_fork_child_reinit_locks at 0x7fdace5bcaf0>

  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 255, in _after_at_fork_child_reinit_locks
    handler._at_fork_reinit()Traceback (most recent call last):
Exception ignored in: 
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 255, in _after_at_fork_child_reinit_locks
<function _after_at_fork_child_reinit_locks at 0x7fdace5bcaf0>
    handler._at_fork_reinit()Exception ignored in: 
<function _after_at_fork_child_reinit_locks at 0x7fdace5bcaf0>Traceback (most recent call last):
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 894, in _at_fork_reinit

  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 255, in _after_at_fork_child_reinit_locks
    self.lock._at_fork_reinit()    
handler._at_fork_reinit()Traceback (most recent call last):
Exception ignored in: 
AttributeError:   File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 255, in _after_at_fork_child_reinit_locks
<function _after_at_fork_child_reinit_locks at 0x7fdace5bcaf0>'NoneType' object has no attribute '_at_fork_reinit'  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 894, in _at_fork_reinit


        handler._at_fork_reinit()
Traceback (most recent call last):
Exception ignored in: self.lock._at_fork_reinit()  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 255, in _after_at_fork_child_reinit_locks
<function _after_at_fork_child_reinit_locks at 0x7fdace5bcaf0>

AttributeError    : handler._at_fork_reinit()'NoneType' object has no attribute '_at_fork_reinit'

Traceback (most recent call last):
      File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 894, in _at_fork_reinit
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 255, in _after_at_fork_child_reinit_locks
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 894, in _at_fork_reinit
        self.lock._at_fork_reinit()self.lock._at_fork_reinit()handler._at_fork_reinit()

Exception ignored in: AttributeErrorAttributeError
: : <function _after_at_fork_child_reinit_locks at 0x7fdace5bcaf0>  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 894, in _at_fork_reinit
'NoneType' object has no attribute '_at_fork_reinit'
'NoneType' object has no attribute '_at_fork_reinit'

    self.lock._at_fork_reinit()Exception ignored in: Traceback (most recent call last):

<function _after_at_fork_child_reinit_locks at 0x7fdace5bcaf0>AttributeError: 
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 255, in _after_at_fork_child_reinit_locks
'NoneType' object has no attribute '_at_fork_reinit'Traceback (most recent call last):
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 894, in _at_fork_reinit
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 894, in _at_fork_reinit

  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 255, in _after_at_fork_child_reinit_locks
                self.lock._at_fork_reinit()handler._at_fork_reinit()self.lock._at_fork_reinit()Exception ignored in: handler._at_fork_reinit()



<function _after_at_fork_child_reinit_locks at 0x7fdace5bcaf0>AttributeErrorAttributeError
: : 'NoneType' object has no attribute '_at_fork_reinit''NoneType' object has no attribute '_at_fork_reinit'Exception ignored in: 

Traceback (most recent call last):
<function _after_at_fork_child_reinit_locks at 0x7fdace5bcaf0>
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 255, in _after_at_fork_child_reinit_locks
Traceback (most recent call last):
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 255, in _after_at_fork_child_reinit_locks
        handler._at_fork_reinit()
handler._at_fork_reinit()
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 894, in _at_fork_reinit
    self.lock._at_fork_reinit()
AttributeError: 'NoneType' object has no attribute '_at_fork_reinit'
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 894, in _at_fork_reinit
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 894, in _at_fork_reinit
        self.lock._at_fork_reinit()
  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 894, in _at_fork_reinit
AttributeErrorself.lock._at_fork_reinit()  File "/home/folder/anaconda3/envs/monai4/lib/python3.9/logging/__init__.py", line 894, in _at_fork_reinit
    self.lock._at_fork_reinit(): 

    AttributeErrorself.lock._at_fork_reinit()
: 'NoneType' object has no attribute '_at_fork_reinit'AttributeError'NoneType' object has no attribute '_at_fork_reinit'AttributeError: 

: 'NoneType' object has no attribute '_at_fork_reinit''NoneType' object has no attribute '_at_fork_reinit'
```

**Comment by jkhenning** [comment]
Hi @demcbs,

Seems this is a python issue: https://bugs.python.org/issue42350

That said, no idea why it tries to fork on `at_exit()` calls? Does that happen only when using clearml?

**Comment by jkhenning** [comment]
Might be related to the process-based reporting clearml uses that perhaps exposes this issue... Can you try setting `sdk.development.report_use_subprocess: false` in your `clearml.conf`?

**Comment by demcbs** [comment]
Sure. Just to be certain, I should copypaste that (right?) into the clearml.conf, at what place?

**Comment by demcbs** [comment]
Ok, tried it, but it did not seem to make any difference.

**Comment by jkhenning** [comment]
Can you show me how you enabled it, just to make sure

**Comment by demcbs** [comment]
Sure, I did: 

![image](https://user-images.githubusercontent.com/46752691/159006412-5c41298f-91a3-4d0d-b7ae-3cd99da991db.png)

and also tried: 

![image](https://user-images.githubusercontent.com/46752691/159006152-fb24727e-d97c-4b8b-b223-11e423486f38.png)

And restarted my jupyter kernel and reran the code.

**Comment by opiolaaleet** [comment]
I get the same error

Exception ignored in: <function _after_at_fork_child_reinit_locks at 0x7fdef5ead120>
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 256, in _after_at_fork_child_reinit_locks
    handler._at_fork_reinit()
  File "/usr/lib/python3.10/logging/__init__.py", line 910, in _at_fork_reinit
    self.lock._at_fork_reinit()
AttributeError: 'NoneType' object has no attribute '_at_fork_reinit'

Python mentions a bug related to that, but it was supposedly fixed 2 years ago. I tried the most recent versions of python 3.10, even nightly build, and the error still shows up. 

It only shows when I use multiple workers in PyTorch data loaders.

Any ideas?

**Comment by opiolaaleet** [comment]
I got it work: the error does not show up if I import the module with my PyTorch model before creating the Task.

**Comment by jkhenning** [comment]
Nice! 👍

**Comment by materight** [comment]
Hi @opiolaaleet, I'm facing the same problem, could you give some more info on what you did to solve it?
