### ISSUE TITLE
Unable to use Azure Cloud Storage as output_uri for the ClearML Tasks

### ISSUE THREAD

**Issue by Bilal-Yousaf** [allegroai/clearml#647]
Hi ClearML Team,

I am trying to use Azore Blob Storage Container as the destination storage by setting the output_uri argument in Task.init function. But I am getting error "".
I think the reason is that my blobstorage is at my own local server hosted behind proxy and I need to define DefaultEndPoint using the connection string when I use (https://pypi.org/project/azure-storage-blob/). But in the clearml.conf I can only find two configuration parameters account_name and account_key. As Clearml also uses azure-storage-blob library it should be able to handle it.

Could you please share how I can pass the connection string or the DefaultEndPoint to hit to use container?

The ClearML config:

    azure.storage {
        containers: [
            {
                account_name: "XXXXX"
                account_key: "XXXXX"
                # container_name: "clear-ml"
            }
        ]
    }

Code Block I am using:
`
task = Task.init(
        project_name='bilal',
        task_name='plotly reporting',
        output_uri='azure://goondiwindiazureblob/clear-ml'
)
`
        
        
   The ERROR I am getting is:
   
ClearML Task: overwriting (reusing) task id=64aa36d8ceae43cb808c7648f86819fc
2022-04-16 07:59:25,913 - clearml.Task - INFO - No repository found, storing script code instead
2022-04-16 08:00:55,153 - clearml.storage - ERROR - Failed uploading: <urllib3.connection.HTTPSConnection object at 0x7f169da22250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
2022-04-16 08:02:17,843 - clearml.storage - WARNING - Storage helper problem for .clearml.test: <urllib3.connection.HTTPSConnection object at 0x7f16bbc75850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
Traceback (most recent call last):
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/storage/helper.py", line 809, in check_write_permissions
    self.delete(path=dest_path)
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/storage/helper.py", line 798, in delete
    return self._driver.delete_object(self._get_object(path))
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/storage/helper.py", line 1921, in delete_object
    container = object.container
AttributeError: 'NoneType' object has no attribute 'container'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    task = Task.init(
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/task.py", line 525, in init
    task.output_uri = output_uri
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/task.py", line 954, in output_uri
    helper.check_write_permissions(value)
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/storage/helper.py", line 811, in check_write_permissions
    raise ValueError('Insufficient permissions for {}'.format(base_url))
ValueError: Insufficient permissions for azure://goondiwindiazureblob/clear-ml

**Comment by jkhenning** [comment]
Hi @Bilal-Yousaf,

(answering here after closing https://github.com/allegroai/clearml-agent/issues/105)

I think the error you're seeing is because you did not configure `container_name` - besides the issue of proxy, why can't you set this value?

**Comment by Bilal-Yousaf** [comment]
After I updated the config to this:
    azure.storage {
        blob_endpoint: "https://blob02.blob.infarm.io/goondiwindiazureblob"
        containers: [
            {
                account_name: "goondiwindiazureblob"
                account_key: "XXXXX"
                container_name: "clear-ml"
            }
        ]
    }
    
    
 I am getting this error:
022-04-17 13:25:23,332 - clearml.storage - ERROR - Failed uploading: <urllib3.connection.HTTPSConnection object at 0x7fecad95fac0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
**2022-04-17 13:26:45,043 - clearml.storage - WARNING - Storage helper problem for .clearml.test: <urllib3.connection.HTTPSConnection object at 0x7fecad9807c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution**
Traceback (most recent call last):
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/storage/helper.py", line 809, in check_write_permissions
    self.delete(path=dest_path)
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/storage/helper.py", line 798, in delete
    return self._driver.delete_object(self._get_object(path))
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/storage/helper.py", line 1921, in delete_object
    container = object.container
AttributeError: 'NoneType' object has no attribute 'container'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    task = Task.init(
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/task.py", line 525, in init
    task.output_uri = output_uri
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/task.py", line 954, in output_uri
    helper.check_write_permissions(value)
  File "/home/bilal/anaconda3/envs/infarm_clearml/lib/python3.8/site-packages/clearml/storage/helper.py", line 811, in check_write_permissions
    raise ValueError('Insufficient permissions for {}'.format(base_url))
ValueError: Insufficient permissions for azure://goondiwindiazureblob/clear-ml

**Comment by Bilal-Yousaf** [comment]
@jkhenning Could you please share your views on this?

**Comment by jkhenning** [comment]
Hi @Bilal-Yousaf, on our TODO to replicate and fix, it's just not a common setup (blob storage behind proxy) so we're not as quick about it 🙁

**Comment by eugen-ajechiloae-clearml** [comment]
@Bilal-Yousaf  I see that you're trying to connect to `azure://goondiwindiazureblob`, where `goondiwindiazureblob` is the account name. Could you try using `azure://blob02.blob.infarm.io/goondiwindiazureblob` (maybe append `/clear-ml` to this) as your connection string? Also, when you encounter DNS resolution errors in general, you could try using the IP the address should resolve to directly, just to check if it really is a DNS problem.

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @Bilal-Yousaf! Do you still have this issue?

**Comment by DavidNativ** [comment]
Hello @Bilal-Yousaf 
Did you manage to achieve your goal ? If you are still facing issues, please let us know, so that we could help you find a solution. 

Thanks
