### ISSUE TITLE
Bug: ClearML and `pytest.capsys`

### ISSUE THREAD

**Issue by alekpikl** [allegroai/clearml#702]
Pytest has `capsys` ([link](https://docs.pytest.org/en/7.1.x/how-to/capture-stdout-stderr.html#accessing-captured-output-from-a-test-function)) option for capturing `stdout` and making it available in the tests.

Unfortunately, this breaks when used with ClearML's automatic logging. 

Stacktrace:
```python
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 164, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 315, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 310, in wrap_session
    config._ensure_unconfigure()
  File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 1004, in _ensure_unconfigure
    fin()
  File "/usr/local/lib/python3.8/dist-packages/_pytest/capture.py", line 666, in stop_global_capturing
    self._global_capturing.pop_outerr_to_orig()
  File "/usr/local/lib/python3.8/dist-packages/_pytest/capture.py", line 552, in pop_outerr_to_orig
    out, err = self.readouterr()
  File "/usr/local/lib/python3.8/dist-packages/_pytest/capture.py", line 597, in readouterr
    err = self.err.snap() if self.err else ""
  File "/usr/local/lib/python3.8/dist-packages/_pytest/capture.py", line 314, in snap
    res = self.tmpfile.getvalue()
  File "/usr/local/lib/python3.8/dist-packages/_pytest/capture.py", line 175, in getvalue
    return self.buffer.getvalue().decode("UTF-8")
ValueError: I/O operation on closed file.
```

**Comment by DavidNativ** [comment]
Hi @alekpikl 
Can you provide some example code please ?

**Comment by alekpikl** [comment]
@DavidNativ here you go:

```bash
pip install pytest clearml
```

```python
"""Run this with:

$ pytest --capture=tee-sys <folder-with-tests>
"""
from clearml import Task
import logging

logger = logging.getLogger('test')


def to_test():
    for i in range(10):
        logger.info(f"Test: {i}.")


def test_smth(capsys):
    Task.set_credentials()  # TODO fill!
    clear_ml_task = Task.init(project_name="tmp/test/", task_name='project')

    # Run code
    to_test()

    # Check
    assert 1 == 1
    out = capsys.readlogerr()
    print(out)

    # Teardown
    clear_ml_task.close()
```

Error that I get:
```python
FAILED                                                                   [100%]

=================================== FAILURES ===================================
__________________________________ test_smth ___________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x7efcd9463940>

    def test_smth(capsys):
        # TODO Init clearml
        Task.set_credentials()
        logger.info("credentials set")
        clear_ml_task = Task.init(project_name="tmp/test/", task_name='project')

        # Run code
        to_test()

        # Check
        assert 1 == 1
>       out = capsys.readlogerr()
E       AttributeError: 'CaptureFixture' object has no attribute 'readlogerr'

test_example.py:45: AttributeError
----------------------------- Captured stdout call -----------------------------
ClearML Task: created new task id=...
ClearML results page: ...
2022-06-21 14:49:01,759 - clearml.Task - INFO - No repository found, storing script code instead
------------------------------ Captured log call -------------------------------
INFO     test:test_example.py:37 credentials set
INFO     test:test_example.py:25 Test: 0.
INFO     test:test_example.py:25 Test: 1.
INFO     test:test_example.py:25 Test: 2.
INFO     test:test_example.py:25 Test: 3.
INFO     test:test_example.py:25 Test: 4.
INFO     test:test_example.py:25 Test: 5.
INFO     test:test_example.py:25 Test: 6.
INFO     test:test_example.py:25 Test: 7.
INFO     test:test_example.py:25 Test: 8.
INFO     test:test_example.py:25 Test: 9.
=========================== short test summary info ============================
FAILED test_example.py::test_smth - AttributeError: 'CaptureFixture' object h...
============================== 1 failed in 1.36s ===============================
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1088, in emit
    stream.write(msg + self.terminator)
  File "/home/alekpikl/.virtualenvs/test/lib/python3.8/site-packages/clearml/backend_interface/logger.py", line 143, in _stdout__patched__write__
    return StdStreamPatch._stdout_proxy.write(*args, **kwargs)
  File "/home/alekpikl/.virtualenvs/test/lib/python3.8/site-packages/clearml/backend_interface/logger.py", line 204, in write
    self._terminal._original_write(message)  # noqa
ValueError: I/O operation on closed file.
Call stack:
  File "/home/alekpikl/.virtualenvs/test/lib/python3.8/site-packages/clearml/task.py", line 3337, in _at_exit
    self.__shutdown()
  File "/home/alekpikl/.virtualenvs/test/lib/python3.8/site-packages/clearml/task.py", line 3428, in __shutdown
    self._wait_for_repo_detection(timeout=10.)
  File "/home/alekpikl/.virtualenvs/test/lib/python3.8/site-packages/clearml/task.py", line 3301, in _wait_for_repo_detection
    self.log.info('Waiting for repository detection and full package requirement analysis')
Message: 'Waiting for repository detection and full package requirement analysis'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1088, in emit
    stream.write(msg + self.terminator)
  File "/home/alekpikl/.virtualenvs/test/lib/python3.8/site-packages/clearml/backend_interface/logger.py", line 143, in _stdout__patched__write__
    return StdStreamPatch._stdout_proxy.write(*args, **kwargs)
  File "/home/alekpikl/.virtualenvs/test/lib/python3.8/site-packages/clearml/backend_interface/logger.py", line 204, in write
    self._terminal._original_write(message)  # noqa
ValueError: I/O operation on closed file.
Call stack:
  File "/home/alekpikl/.virtualenvs/test/lib/python3.8/site-packages/clearml/task.py", line 3337, in _at_exit
    self.__shutdown()
  File "/home/alekpikl/.virtualenvs/test/lib/python3.8/site-packages/clearml/task.py", line 3428, in __shutdown
    self._wait_for_repo_detection(timeout=10.)
  File "/home/alekpikl/.virtualenvs/test/lib/python3.8/site-packages/clearml/task.py", line 3311, in _wait_for_repo_detection
    self.log.info('Finished repository detection and package analysis')
Message: 'Finished repository detection and package analysis'
Arguments: ()
```

**Comment by DavidNativ** [comment]
thanks. let me play a bit with this. i keep you updated

**Comment by alekpikl** [comment]
> how to run it (for ex. the kind of stuffs into )

What do you mean? 

You can run it with `pytest --capture=tee-sys FOLDER_WITH_THE_TEST`. 

We use pytest to perform end2end tests of our training pipeline. 

I don't think this is related to #697. 

My hunch is that it is related to how Pytest and ClearML capture `stdout/stderr`. The error occurs at `shutdown` of clearml.

**Comment by erezalg** [comment]
@alekpikl,

Thanks :) I was able to reproduce the exception. I think you're right, something that we do collides with something pytest is doing. 

Just want to make sure, I'm still getting an error on pytest when I remove the Task.init(), is this the expected behavior? 

`(p3.8) erez@jane-pc:~/source/junk/testing_tests$ pytest --capture=tee-sys something.py 
================================================= test session starts ==================================================
platform linux -- Python 3.8.0, pytest-7.1.2, pluggy-0.13.1
rootdir: /home/erez/source/junk/testing_tests
plugins: hydra-core-1.1.2, regressions-2.1.1, datadir-1.3.1, requests-mock-1.7.0
collected 1 item                                                                                                       

something.py erez
F                                                                                                   [100%]

======================================================= FAILURES =======================================================
______________________________________________________ test_smth _______________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x7faaeed1eeb0>

    def test_smth(capsys):
        #Task.set_credentials()  # TODO fill!
        #clear_ml_task = Task.init(project_name='erez', task_name='erez')
        print('erez')
        # Run code
        to_test()
    
        # Check
        assert 1 == 1
>       out = capsys.readlogerr()
E       AttributeError: 'CaptureFixture' object has no attribute 'readlogerr'

something.py:21: AttributeError
------------------------------------------------- Captured stdout call -------------------------------------------------
erez
=============================================== short test summary info ================================================
FAILED something.py::test_smth - AttributeError: 'CaptureFixture' object has no attribute 'readlogerr'
================================================== 1 failed in 0.74s ===================================================
`

**Comment by alekpikl** [comment]
I just realized that the error is that `readlogerr` (doesn't exist). It should be `readouterr` 🤦 . 

The clearml error happened while handling ☝️  error, so I guess this issue can be closed. 

I'm sorry for the time but thanks for leading me to the actual problem. :)
