### ISSUE TITLE
Bug: base url with s3 failed in check_write_permissions

### ISSUE THREAD

**Issue by Shm013** [allegroai/clearml#706]
I have error in `check_write_permissions` when set 3S target as `default_output_uri` after this commit https://github.com/allegroai/clearml/commit/21712a709d052a2bd62f1324b7c1fa928dbd6ece#diff-bc25f5894da3c404d2b542d9da72ed37c7a42522b4032f2530beaf560210b653 

```
Traceback (most recent call last):
  File "/home/shm/Documents/project/CMLP/examples/./clearml_test_local.py", line 9, in <module>
    task = Task.init(project_name="great project", task_name="best experiment")
  File "/home/shm/Documents/project/CMLP/examples/venv/lib/python3.9/site-packages/clearml/task.py", line 602, in init
    task.output_uri = cls.__default_output_uri
  File "/home/shm/Documents/project/CMLP/examples/venv/lib/python3.9/site-packages/clearml/task.py", line 1084, in output_uri
    helper.check_write_permissions(value)
  File "/home/shm/Documents/project/CMLP/examples/venv/lib/python3.9/site-packages/clearml/storage/helper.py", line 851, in check_write_permissions
    err_msg = 'Insufficient permissions ({} failed) for ' + base_url
  File "/home/shm/Documents/project/CMLP/examples/venv/lib/python3.9/site-packages/clearml/utilities/proxy_object.py", line 286, in method
    mtd = getattr(obj, name)
AttributeError: 'str' object has no attribute '__radd__'
```

It fixes with
```
err_msg = 'Insufficient permissions ({} failed) for ' + str(base_url)
```

in 847 line clearml/storage/helper.py

**Comment by jkhenning** [comment]
Hi @Shm013 ,

Can you please try using v1.6.2rc0 and see if it solves your issue?

**Comment by Shm013** [comment]
v1.6.2rc0 works fine!
1.6.0 and 1.6.1 - are failed.

**Comment by Shm013** [comment]
I can't find any changes in code that involved with this bug.
How do you fixed that?

**Comment by jkhenning** [comment]
Hi @Shm013,

I'll be releasing the formal version today and updating the code, it was basically solved by changing the format string construction to using a safer conversion (as the `+` operator caused issues with the URL value that might be lazily loaded)

**Comment by jkhenning** [comment]
@Shm013 v1.6.2 is out 🙂
