### ISSUE TITLE
Pipeline that invokes a step function twice will crash if cloned and run from the UI

### ISSUE THREAD

**Issue by tonyd** [allegroai/clearml#769]
## Describe the bug
If a pipeline created with decorators invokes the same step function twice, two step tasks are correctly created, the second having "_1" appended to its name. However, if that pipeline is then cloned and run via the UI, execution will fail with a crash.

The problem occurs because the cloned pipeline task has a configuration for the second, "XXX_1" step, but there is no `task_factory_func`. This field is properly filled in for the first "XXX" step because it is established when the pipeline decorators are executed, and the configuration is merged on top of that.

## To reproduce
This test code creates the pipeline by running locally, but the cloned pipeline run needs two workers connected to the "default" queue. This code must be available to the worker via a Git repository.
```
from clearml.automation.controller import PipelineDecorator
from clearml import TaskTypes, Task


@PipelineDecorator.component(return_values=['data_frame'], cache=True, task_type=TaskTypes.data_processing)
def step_one(mock_parameter='mock'):
    print('step_one')
    import pandas as pd
    data_frame = pd.DataFrame()
    return data_frame


@PipelineDecorator.pipeline(name='custom pipeline logic', project='examples', version='0.0.5')
def executing_pipeline(mock_parameter='mock'):
    # Use the pipeline argument to start the pipeline and pass it ot the first step
    print('launch step one')
    data_frame = step_one(mock_parameter)
    data_frame = step_one(mock_parameter + '_2')

    return Task.current_task()


if __name__ == '__main__':
    # Run locally to create a new pipeline instance and have it complete before returning from the function call.
    PipelineDecorator.run_locally()

    task = executing_pipeline()

    from clearml.backend_api.services.v2_20.queues import GetDefaultRequest
    queue_id = task.send(GetDefaultRequest()).response.id

    # Clone and start a new instance of this pipeline; this is the same call the UI makes.
    from clearml.backend_api.services.v2_20.pipelines import StartPipelineRequest
    req = StartPipelineRequest(task=task.id, queue=queue_id)
    resp = task.send(req).response
    new_task_id = resp.pipeline

    print("started new pipeline {}".format(new_task_id))

    # Wait for the new pipeline to execute.
    from clearml.backend_api.services.v2_20.events import GetTaskLogRequest
    import time

    while True:
        task = Task.get_task(task_id=new_task_id)
        if task.status not in [Task.TaskStatusEnum.created, Task.TaskStatusEnum.queued, Task.TaskStatusEnum.in_progress]:
            break
        print("task {} status {}...waiting".format(new_task_id, task.status))
        time.sleep(3)

    if task.status == Task.TaskStatusEnum.failed:
        print("task FAILED")
        for event in task.send(GetTaskLogRequest(task=task.id, order='asc')).response.events:
            if 'Traceback' in event['msg']: print(event['msg'])

    print('process completed')
```

## Expected behaviour
The second pipeline execution, started above using the REST API to mimic the UI, fails with this traceback (printed out by test code or visible in the UI):
```
Traceback (most recent call last):
  File "/home/ec2-user/.clearml/venvs-builds/3.9/task_repository/clearml.git/examples/pipeline/test_run_pipeline.py", line 27, in <module>
    task = executing_pipeline()
  File "/home/ec2-user/.clearml/venvs-builds/3.9/lib/python3.9/site-packages/clearml/automation/controller.py", line 3457, in internal_decorator
    a_pipeline._start(wait=False)
  File "/home/ec2-user/.clearml/venvs-builds/3.9/lib/python3.9/site-packages/clearml/automation/controller.py", line 1213, in _start
    self._prepare_pipeline(step_task_completed_callback, step_task_created_callback)
  File "/home/ec2-user/.clearml/venvs-builds/3.9/lib/python3.9/site-packages/clearml/automation/controller.py", line 1247, in _prepare_pipeline
    if not self._verify():
  File "/home/ec2-user/.clearml/venvs-builds/3.9/lib/python3.9/site-packages/clearml/automation/controller.py", line 1496, in _verify
    self._verify_node(node)
  File "/home/ec2-user/.clearml/venvs-builds/3.9/lib/python3.9/site-packages/clearml/automation/controller.py", line 1512, in _verify_node
    raise ValueError("Node '{}', base_task_id is empty".format(node.name))
ValueError: Node 'step_one_1', base_task_id is empty
```

## Environment
* app.clear.ml
* ClearML SDK Version: 1.6.4
* Python Version: 3.9.12
* local:MacOS 12.5, workers: Amazon Linux 2

**Comment by pollfly** [comment]
Hey @tonyd! Just letting you know that this issue has been resolved in the recently released [v.1.7.2](https://github.com/allegroai/clearml/releases/tag/v1.7.2). Let us know if there are any issues :)

**Comment by jkhenning** [comment]
Closing this issue. Please reopen if it's still relevant.
