### ISSUE TITLE
Unable to Connect to ClearML Server hosted on Virtual Machine behind a proxy server.

### ISSUE THREAD

**Issue by hadiairshadW** [allegroai/clearml#778]
Hi, 
I have clearml server hosted on a virtual machine and can only create tasks when I run the code on that machine or any machine on the local network using the below config. 
          api_server: http://localhost:8008
           web_server: http://localhost:8080
           files_server: http://localhost:8081

When I use the following configuration for the clearML config it throws error
    api_server: http://****.files.infarm.io
    web_server: http://****.infarm.io
    files_server: http://****.api.infarm.io

All of these urls are mapped to specific ports as mentions:
    api_server: http://****.files.infarm.io  mapped to 8008
    web_server: http://****.infarm.io    mapped to 8080
    files_server: http://****.api.infarm.io  mapped to 8081

**I think the error is because the ports are not mentioned in the global address we are using in the config or is it some other issue?**
 
Error Stack:
"time": "2022-09-13 16:56:13,775", "level": "INFO", "message": "NumExpr defaulting to 8 threads."}
{"time": "2022-09-13 16:56:21,010", "level": "WARNING", "message": "Retrying (Retry(total=239, connect=239, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f24b9d9d070>, 'Connection to clearml.files.infarm.io timed out. (connect timeout=3.0)')': /auth.login"}
2022-09-13 16:56:37,458 - clearml.Task - ERROR - Action failed <400/12: tasks.create/v1.0 (Validation error (error for field 'name'. field is required!))> (name=classification, system_tags=['development'], type=training, comment=Auto-generated at 2022-09-13 11:56:28 UTC by hadia@wortel-dev, project=2ecfc7efcda448a6b6e7de61c8553ba1, input={'view': {}})
Traceback (most recent call last):
  File "/home/hadia/workspace/Infarm/code/TrainingPipeline/examples/example_train.py", line 21, in <module>
    manager = PipelineManager(
  File "/home/hadia/workspace/Infarm/code/TrainingPipeline/./src/pytorch_trainer/pipelinemanager.py", line 37, in __init__
    self.clearml_handler = ClearMlHandler(self.config["clearmlTask"])
  File "/home/hadia/workspace/Infarm/code/TrainingPipeline/./src/pytorch_trainer/logger/clearml_handler.py", line 13, in __init__
    self.task = Task.init(
  File "/home/hadia/anaconda3/envs/infarm_env/lib/python3.9/site-packages/clearml/task.py", line 583, in init
    task = cls._create_dev_task(
  File "/home/hadia/anaconda3/envs/infarm_env/lib/python3.9/site-packages/clearml/task.py", line 3035, in _create_dev_task
    task = cls(
  File "/home/hadia/anaconda3/envs/infarm_env/lib/python3.9/site-packages/clearml/task.py", line 183, in __init__
    super(Task, self).__init__(**kwargs)
  File "/home/hadia/anaconda3/envs/infarm_env/lib/python3.9/site-packages/clearml/backend_interface/task/task.py", line 172, in __init__
    self.id = self._auto_generate(project_name=project_name, task_name=task_name, task_type=task_type)
  File "/home/hadia/anaconda3/envs/infarm_env/lib/python3.9/site-packages/clearml/backend_interface/task/task.py", line 352, in _auto_generate
    res = self.send(req)
  File "/home/hadia/anaconda3/envs/infarm_env/lib/python3.9/site-packages/clearml/backend_interface/base.py", line 109, in send
    return self._send(session=self.session, req=req, ignore_errors=ignore_errors, raise_on_errors=raise_on_errors,
  File "/home/hadia/anaconda3/envs/infarm_env/lib/python3.9/site-packages/clearml/backend_interface/base.py", line 103, in _send
    raise SendError(res, error_msg)
clearml.backend_interface.session.SendError: Action failed <400/12: tasks.create/v1.0 (Validation error (error for field 'name'. field is required!))> (name=classification, system_tags=['development'], type=training, comment=Auto-generated at 2022-09-13 11:56:28 UTC by hadia@wortel-dev, project=2ecfc7efcda448a6b6e7de61c8553ba1, input={'view': {}})

**Comment by jkhenning** [comment]
Hi @hadiairshadW,

I'm not sure I understand, what exactly is configured in your clearml.conf file?

Can you try to `curl` any of these addresses you have there?

**Comment by hadiairshadW** [comment]
Yes, I tried Curl command. It returns following response.

![curl_output](https://user-images.githubusercontent.com/109482052/190406791-bd002014-aae1-4534-8883-9cbce9c89c9f.png)
