### ISSUE TITLE
pymongo.errors.OperationFailure: BSON field 'update.updates.u' is the wrong type 'array', expected type 'object', full error: {'ok': 0.0, 'errmsg': "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", 'code': 14, 'codeName': 'TypeMismatch'}

### ISSUE THREAD

**Issue by jakubmuransky** [allegroai/clearml#863]
Full Error:
`[ERROR] [clearml.service_repo] Update failed (BSON field 'update.updates.u' is the wrong type 'array', expected type 'object', full error: {'ok': 0.0, 'errmsg': "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", 'code': 14, 'codeName': 'TypeMismatch'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 578, in update
    result = update_func(query, update, upsert=upsert)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 1033, in update_one
    hint=hint, session=session),
  File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 879, in _update_retryable
    _update, session)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/mongo_client.py", line 1552, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 875, in _update
    retryable_write=retryable_write)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 845, in _update
    retryable_write=retryable_write).copy()
  File "/usr/local/lib64/python3.6/site-packages/pymongo/pool.py", line 721, in command
    exhaust_allowed=exhaust_allowed)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/network.py", line 160, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: BSON field 'update.updates.u' is the wrong type 'array', expected type 'object', full error: {'ok': 0.0, 'errmsg': "BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'", 'code': 14, 'codeName': 'TypeMismatch'}`

## Environment
* self-hosted in docker
* WebApp: 1.9.0-293 • Server: 1.9.0-293 • API: 2.2
* Centos8 Stream

**Comment by erezalg** [comment]
Hi @jakubmuransky,

Can you please let me know when are you getting this error? What are you doing and where is this print appearing?

**Comment by jakubmuransky** [comment]
During the training, everything is logged but in console is this error, same in docker logs of clearml-apiserver.
I double-checked docker-compose and I have older version mongo:3.6.5, could it be the problem of this ?

**Comment by jkhenning** [comment]
Hi @jakubmuransky, 

I assume you did not go through the MongoDB migration when upgrading your ClearML Server?

**Comment by ito-innovatrics** [comment]
Yesterday I upgraded mongoDB to newest version on that instance, I'll let you know if it's working or not...

**Comment by tkupek** [comment]
I had the same problem. After applying the mongoDB upgrade described in https://clear.ml/docs/latest/docs/deploying_clearml/clearml_server_mongo44_migration/#completing-the-installation the issue was solved.

**Comment by jakubmuransky** [comment]
Sorry I forgot the answer. After DB upgrade it has been working.
