### ISSUE TITLE
[Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by Robotatron** [allegroai/clearml#898]
Add two magic lines, worked fine yesterday.
Today, no change to the code, getting this error:

```
Retrying (Retry(total=239, connect=239, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0a2c3a820>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /auth.login
Retrying (Retry(total=238, connect=238, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0a2c74b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /auth.login
Retrying (Retry(total=237, connect=237, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0a2c83bb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /auth.login
Retrying (Retry(total=236, connect=236, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0a2c83d60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /auth.login
Retrying (Retry(total=235, connect=235, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0a2c3a9a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /auth.login
Retrying (Retry(total=234, connect=234, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0a2c3ab20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /auth.login
^CTraceback (most recent call last):
  File "/opt/conda/envs/detectron2/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/conda/envs/detectron2/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/conda/envs/detectron2/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by Robotatron** [comment]
Fixed it by adding more DNS servers

**Comment by Robotatron** [comment]
Have this issue again :(

**Comment by ainoam** [comment]
@Robotatron A network infrastructure issue was interfering with the ClearML service. Our systems show that this problem should be resolved by now.

**Comment by Robotatron** [comment]
Thanks. Is there a status page to see the health of the services in the future?

**Comment by ainoam** [comment]
@Robotatron Not yet, Though in this case the service was affected with DNS issues outside our control.

Checking the ClearML [Slack channels](https://join.slack.com/t/clearml/shared_invite/zt-1kvcxu5hf-SRH_rmmHdLL7l2WadRJTQg) is recommended for latest updates and notifications.
