### ISSUE TITLE
Pandas Dataframe error in remote execution mode

### ISSUE THREAD

**Issue by meanna** [allegroai/clearml#925]
When I run the code with remote execution mode, I get this problem when importing` Task`.
Here is the code I use in my script.
```
import pandas as pd
from clearml import Task
...
task = Task.init( ...)
task.execute_remotely(queue_name="default", clone=False, exit_process=True)
```

However,  when I run my code with `clearml-task `CLI, it works fine. This seems like a bug.

I also observe that when I do not import pandas (when not using clearml-task), this problem is gone.
```
Traceback (most recent call last):
  File "/root/.clearml/venvs-builds/3.8/code/text_classification.py", line 12, in <module>
    from clearml import Task
  File "/root/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/__init__.py", line 5, in <module>
    from .task import Task
  File "/root/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/task.py", line 45, in <module>
    from .backend_interface.metrics import Metrics
  File "/root/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_interface/__init__.py", line 2, in <module>
    from .task import Task
  File "/root/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_interface/task/__init__.py", line 1, in <module>
    from .task import Task
  File "/root/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/backend_interface/task/task.py", line 32, in <module>
    from ...binding.artifacts import Artifacts
  File "/root/.clearml/venvs-builds/3.8/lib/python3.8/site-packages/clearml/binding/artifacts.py", line 32, in <module>
    DataFrame = pd.DataFrame
AttributeError: module 'pandas' has no attribute 'DataFrame'
```

https://github.com/allegroai/clearml/blob/e938f2800bb774e2bece2c5a5ec578037874608c/clearml/binding/artifacts.py#L32

**Comment by meanna** [comment]
I know the problem now. Clearml installed pandas version I used in my local env instead of what specified in requirements.txt.

It seems to ignores` task.add_requirements('requirements.txt')`
