### ISSUE TITLE
Invalid syntax in MetricsEventAdapter.__init__()

### ISSUE THREAD

**Issue by lrnzthl** [allegroai/clearml#960]
**Got this SyntaxError by calling:** 
`clearml-task --project x --name y --repo https://github.com/allegroai/clearml --branch master --script /examples/optimization/hyper-paramete
r-optimization/base_template_keras_simple.py --queue default`

**Error message:**
`
Traceback (most recent call last):
  File "/root/.clearml/venvs-builds/3.10/task_repository/clearml/examples/optimization/hyper-parameter-optimization/base_template_keras_simple.py", line 9, in <module>
    from clearml import Task
  File "/root/.clearml/venvs-builds/3.10/task_repository/clearml/clearml/__init__.py", line 5, in <module>
    from .task import Task
  File "/root/.clearml/venvs-builds/3.10/task_repository/clearml/clearml/task.py", line 44, in <module>
    from .backend_interface.metrics import Metrics
  File "/root/.clearml/venvs-builds/3.10/task_repository/clearml/clearml/backend_interface/__init__.py", line 2, in <module>
    from .task import Task
  File "/root/.clearml/venvs-builds/3.10/task_repository/clearml/clearml/backend_interface/task/__init__.py", line 1, in <module>
    from .task import Task
  File "/root/.clearml/venvs-builds/3.10/task_repository/clearml/clearml/backend_interface/task/task.py", line 32, in <module>
    from ...binding.artifacts import Artifacts
  File "/root/.clearml/venvs-builds/3.10/task_repository/clearml/clearml/binding/artifacts.py", line 23, in <module>
    from ..backend_interface.metrics.events import UploadEvent
  File "/root/.clearml/venvs-builds/3.10/task_repository/clearml/clearml/backend_interface/metrics/__init__.py", line 2, in <module>
    from .interface import Metrics
  File "/root/.clearml/venvs-builds/3.10/task_repository/clearml/clearml/backend_interface/metrics/interface.py", line 16, in <module>
    from .events import MetricsEventAdapter
  File "/root/.clearml/venvs-builds/3.10/task_repository/clearml/clearml/backend_interface/metrics/events.py", line 80
    def __init__(self, metric, variant, iter=None, timestamp=None, task=None, gen_timestamp_if_none=True, , model_event=None):
                                                                                                          ^
SyntaxError: invalid syntax
`

https://github.com/allegroai/clearml/blob/5635137972e14300bd463b19fd6a3f8cf1437639/clearml/backend_interface/metrics/events.py#L80

**Comment by ainoam** [comment]
Hi @lrnzthl,

Which version of clearml are you using?

There's seems to be a superfluous whitespace in your script path when invoking clearml-task: "hyper-paramete r-optimization" - Is it merely a type-o in reporting the issue, or was that present in the original invocation?
